let ar = {
    "Language": "لغة",
    "Show Time Zone": "إظهار المنطقة الزمنية",
    "Custom Local Settings": "الإعدادات المحلية المخصصة",
    "Add and showcase events on your site using a beautiful calendar.": "قم بإضافة وعرض الأحداث على موقعك باستخدام تقويم جميل . ",
    "Week Days": "أيام الأسبوع",
    "Manage Events": "إدارة الأحداث",
    "General": "جنرال لواء",
    "Layout Picker": "منتقي التخطيط",
    "Month": "شهر",
    "Monthly": "شهريا",
    "Week": "أسبوع",
    "Weekly": "أسبوعي",
    "Day": "يوم",
    "Daily": "اليومي",
    "Agenda": "جدول أعمال",
    "Navigation Buttons": "أزرار التنقل",
    "Today": "اليوم",
    "Week numbers": "أرقام الأسبوع",
    "Include Weekends": "تضمين عطلات نهاية الأسبوع",
    "All-day": "طوال اليوم",
    "All Day": "طوال اليوم",
    "Label": "ضع الكلمة المناسبة",
    "Fit to Height": "يصلح للارتفاع",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "لتعيين نسب التطبيق تعطيل هذا الخيار يدويًا وتغيير حجم التقويم في محرر. ",
    "Default Layout": "التخطيط الافتراضي",
    "Monthly view": "العرض الشهري",
    "Weekly and Daily view": "العرض الأسبوعي واليومي",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "يمكنك منح الزائرين تجربة أكثر اتساقًا من خلال إظهار نفس العدد من الأسابيع ( 6) في المرة الواحدة.",
    "Fixed Weekly Layout": "تخطيط أسبوعي ثابت",
    "back": " العودة ",
    "Row": "صف",
    "Hours in Weekly View": "الساعات في العرض الأسبوعي",
    "Hours in Daily View": "الساعات في العرض اليومي",
    "Start": "بداية",
    "End": "النهاية",
    "At This Hour": "في هذه الساعة",
    "Add to": "اضف إليه",
    "Button": "زر",
    "Buttons": "وصفت",
    "Sunday": "الأحد",
    "Monday": "الإثنين",
    "Tuesday": "الثلاثاء",
    "Wednesday": "الأربعاء",
    "Thursday": " الخميس ",
    "Friday": "يوم الجمعة",
    "Saturday": "يوم السبت",
    "Default Date": "التاريخ الافتراضي",
    "year": " السنة ",
    "month": " الشهر ",
    "days": " الأيام ",
    "ago": " قبل ",
    "ahead": " أمام ",
    "Yesterday": "في الامس",
    "Today": "اليوم",
    "Tomorrow": "غدا",
    "Custom": "العادة",
    "Set Daily Rows Limit": "تعيين حد الصفوف اليومية",
    "Set Proportions": "تعيين النسب",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "السماح للزائر بإضافة حدث إلى Calnedars المحلي , Google و Yahoo و Outlook و ICalendar . ",
    "Container": "حاوية",
    "Background": "خلفية",
    "Container Background": "خلفية الحاوية",
    "Container Borders": "حدود الحاوية",
    "Calendar": "التقويم",
    "Event Info Tooltip": "تلميح معلومات الحدث",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "عندما يحوم الناس فوق حدث ما ، سيرون كل المعلومات المتعلقة به في تلميح الأدوات. ",
    "Event Info Window": "نافذة معلومات الحدث",
    "This is the full information window that opens when someone clicks on the event.": "هذه هي نافذة المعلومات الكاملة التي تفتح عندما ينقر شخص ما على الحدث. ",
    "Use Gradient": "استخدم التدرج اللوني",
    "Vertical": "عمودي",
    "Horizontal": "أفقي",
    "First": "أول",
    "Second": "ثانيا",
    "diagonal": " قطري ",
    "Radial": "شعاعي",
    "Select option": "حدد خيار",
    "Solid": "صلب",
    "Dotted": "منقط",
    "Dashed": "متقطع",
    "Double": "مزدوج",
    "Border Radius": "نصف قطر الحدود",
    "Padding": "حشوة",
    "Date Header": "عنوان التاريخ",
    "Event Default Color": "اللون الافتراضي للحدث",
    "Days of Week": "ايام الاسبوع",
    "Days of Week Background": "أيام الأسبوع الخلفية",
    "Date": "تاريخ",
    "Event Title": "عنوان الحدث",
    "Highlight today": "تسليط الضوء اليوم",
    "Highlight Color": "تسليط الضوء على اللون",
    "Hide": "إخفاء",
    "Calendar Border Color": "لون حدود التقويم",
    "Calendar Border Width": "عرض حدود التقويم",
    "Calendar Border Style": "نمط حدود التقويم",
    "Font Color": "لون الخط",
    "Event Background": "خلفية الحدث",
    "Card Date Color": "لون تاريخ البطاقة",
    "Title Font": "الخط عنوان",
    "Date Font": "خط التاريخ",
    "Description Font": "خط الوصف",
    "Button Background": "زر الخلفية",
    "Button Text": "زر كتابة",
    "Border Color": "لون الحدود",
    "Border Width": "عرض الحدود",
    "Border Type": "نوع الحدود",
    "Title": "عنوان",
    "Description": "وصف",
    "Background Color": "لون الخلفية",
    "Divider": "مقسم",
    "Event Details Font": "خط تفاصيل الحدث",
    "Website Link Color": "لون رابط الموقع",
    "Developer Info": "معلومات المطور",
    "User Guide": "دليل المستخدم",
    "Support e-mail": "دعم البريد الإلكتروني",
    "Our Website": "موقعنا على الانترنت",
    "App Review": "مراجعة التطبيقات",
    "Enjoying App? Leave us a review in the App Market.": "استمتع بالتطبيق؟ اترك لنا مراجعة في سوق التطبيقات. ",
    "Review Us": "راجعنا",
    "Connect With Us": "اتصل بنا",
    "What's your email?": "ما هو بريدك الإلكتروني؟ ",
    "Invalid email address!": "عنوان بريد إلكتروني غير صالح! ",
    "Comments": "تعليقات",
    "We'd love to hear from you. Send us a message.": "نود أن نسمع منك. أرسل لنا رسالة. ",
    "Message must be at least 5 characters long": "يجب ألا يقل طول الرسالة عن 5 أحرف",
    "Send": "إرسال",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "إذا كنت تريد السماح للمستخدم بالتبديل بين طرق عرض التقويم ، فقم بتمكين هذا الخيار واختر طرق العرض التي تريد عرضها. ",
    "Main": "الأساسية",
    "Localize": "تمركز",
    "Settings": "الإعدادات",
    "Layouts": "تخطيطات",
    "Advanced": "المتقدمة",
    "Design": "التصميم",
    "Support": "الدعم",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "تعتمد جميع الإعدادات المحلية (تلقائيًا) على لغتك. إذا كانت لغتك في القائمة ، فليست هناك حاجة لتخصيص هذا القسم.",
    "Date Format": "صيغة التاريخ",
    "Time Format": "تنسيق الوقت",
    "Text Direction": "اتجاه النص",
    "Left to Right": "من اليسار إلى اليمين",
    "Right to Left":"من اليمين الى اليسار",
    "Week Starts On": "يبدأ الأسبوع",
    "Agenda Style": "نمط جدول الأعمال",
    "Classic": "كلاسيك",
    "Modern": "مودرن",
    "Agenda Header": "جدول الأعمال",
    "Upcoming Events": "الأحداث القادمة",
    "Upgrade now and get a lot more features and enjoy your APP in full!": "قم بالترقية الآن واحصل على المزيد من الميزات واستمتع بتطبيقك بالكامل!",
    "Upgrade Now": "تحديث الآن",
    "Hosting events that last all day? This lets you show them on your calendar.":"استضافة الأحداث التي تستمر طوال اليوم؟ يتيح لك ذلك إظهارها في التقويم الخاص بك.",
    "24 hours":"24 ساعة",
    "Sat": "يوم السبت",
    "Sun": "الأحد",
    "Mon": "الإثنين",
    "Default":"الافتراضي",
    "Select custom design style for your calendar.":"حدد نمط تصميم مخصص للتقويم الخاص بك.",
    "Style":"قلم المدقة",
    "Styles and Colors": "الأنماط والألوان",
    "Calendar Name":"اسم التقويم",
    "Write your Calendar name here":"اكتب اسم التقويم الخاص بك هنا",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"هذا غير مرئي للمستخدمين. قم بتعيين أسماء للتمييز بين التقاويم الخاصة بك عند استخدام وظيفة Boom Calendar Sync.",
    "General Info" : "معلومات عامة",
    "Venue" : "مكان",
    "Organizer"  : "منظم"
};

export default ar;
