let bg = {
    "Language": "Език",
    "Show Time Zone": "Показване на часовата зона",
    "Custom Local Settings": "Персонализирани локални настройки",
    "Add and showcase events on your site using a beautiful calendar.": "Добавете и покажете събития на вашия сайт с помощта на красив календар .",
    "Week Days": "Седмични дни",
    "Manage Events": "Управление на събития",
    "General": "Общ",
    "Layout Picker": "Избор на оформление",
    "Month": "Месец",
    "Monthly": "Месечно",
    "Week": "Седмица",
    "Weekly": "Cедмично",
    "Day": "Ден",
    "Daily": "Дейли",
    "Agenda": "Дневен ред",
    "Navigation Buttons": "Бутони за навигация",
    "Today": "Днес",
    "Week numbers": "Седмични номера",
    "Include Weekends": "Включване на уикендите",
    "All-day": "Цял ден",
    "All Day": "Цял ден",
    "Label": "Етикет",
    "Fit to Height": "Подходящ на височина",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "За да зададете пропорциите на приложението, деактивирайте тази опция и промените размера на календара в редактора.",
    "Default Layout": "Оформление по подразбиране",
    "Monthly view": "Месечен изглед",
    "Weekly and Daily view": "Седмичен и дневен изглед",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Можете да дадете на посетителите по- последователно изживяване, като показвате един и същ брой седмици( 6) наведнъж.",
    "Fixed Weekly Layout": "Фиксирана седмична оформление",
    "back": " назад ",
    "Row": "Ред",
    "Hours in Weekly View": "Часове в седмичен изглед",
    "Hours in Daily View": "Часове в ежедневен изглед",
    "Start": "Старт",
    "End": "Край",
    "At This Hour": "В този час",
    "Add to": "Добави към",
    "Button": "Бутон",
    "Buttons": "Бутони",
    "Sunday": "В неделя",
    "Monday": "Понеделник",
    "Tuesday": "Вторник",
    "Wednesday": "Сряда",
    "Thursday": " Четвъртък ",
    "Friday": "Петък",
    "Saturday": "Събота",
    "Default Date": "Дата по подразбиране",
    "year": " година ",
    "month": " месец ",
    "days": " дни ",
    "ago": " преди ",
    "ahead": " напред ",
    "Yesterday": "Вчера",
    "Today": "Днес",
    "Tomorrow": "Утре",
    "Custom": "Персонализиран",
    "Set Daily Rows Limit": "Задайте лимит на дневните редове",
    "Set Proportions": "Задаване на пропорции",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Разрешете на посетителя да добави събитие към местните Calnedars, Google, Yahoo, Outlook, ICalendar .",
    "Container": "Контейнер",
    "Background": "Заден план",
    "Container Background": "Фон на контейнера",
    "Container Borders": "Граници на контейнери",
    "Calendar": "Календар",
    "Event Info Tooltip": "Подсказка за информация за събитието",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "Когато хората задръжте курсора на дадено събитие, те ще видят цялата информация за него в подсказка.",
    "Event Info Window": "Прозорец за информация за събитието",
    "This is the full information window that opens when someone clicks on the event.": "Това е пълният информационен прозорец, който се отваря, когато някой кликне върху събитието.",
    "Use Gradient": "Използвайте градиент",
    "Vertical": "Вертикална",
    "Horizontal": "Хоризонтално",
    "First": "На първо място",
    "Second": "Втора",
    "diagonal": " диагонал ",
    "Radial": "Радиално",
    "Select option": "Изберете опция",
    "Solid": "Solid",
    "Dotted": "Пунктирана",
    "Dashed": "Дяволски",
    "Double": "Double",
    "Border Radius": "Граничен радиус",
    "Padding": "Празно",
    "Date Header": "Заглавие на дата",
    "Event Default Color": "Цвят по подразбиране на събитието",
    "Days of Week": "Дни от седмицата",
    "Days of Week Background": "Дни на седмицата",
    "Date": "Дата",
    "Event Title": "Заглавие на събитието",
    "Highlight today": "Отбележете днес",
    "Highlight Color": "Цвят на подчертаване",
    "Hide": "Крия",
    "Calendar Border Color": "Цвят на границата на календара",
    "Calendar Border Width": "Ширина на границата на календара",
    "Calendar Border Style": "Календар на границата на календара",
    "Font Color": "Цвят на шрифта",
    "Event Background": "Фон на събитието",
    "Card Date Color": "Цвят на датата на картата",
    "Title Font": "Шрифт на заглавието",
    "Date Font": "Шрифт за дата",
    "Description Font": "Шрифт с описание",
    "Button Background": "Фон на бутона",
    "Button Text": "Текст на бутона",
    "Border Color": "Цвят на границата",
    "Border Width": "Ширина на границата",
    "Border Type": "Тип граница",
    "Title": "Заглавие",
    "Description": "Описание",
    "Background Color": "Цвят на фона",
    "Divider": "Разделител",
    "Event Details Font": "Шрифт за подробности за събитието",
    "Website Link Color": "Цвят на връзката към уебсайта",
    "Developer Info": "Информация за програмисти",
    "User Guide": "Упътване за употреба",
    "Support e-mail": "Поддръжка на имейл",
    "Our Website": "Нашият уебсайт",
    "App Review": "Преглед на приложението",
    "Enjoying App? Leave us a review in the App Market.": "Наслаждавате се на приложението? Оставете ни преглед в App Market.",
    "Review Us": "Прегледайте ни",
    "Connect With Us": "Свържи се с нас",
    "What's your email?": "Какъв е вашият имейл?",
    "Invalid email address!": "Невалиден имейл адрес! ",
    "Comments": "Коментари",
    "We'd love to hear from you. Send us a message.": "Ще се радваме да се свържем с вас.Изпратете ни съобщение.",
    "Message must be at least 5 characters long": "Съобщението трябва да е поне 5 знака",
    "Send": "Изпрати",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Ако искате да се даде възможност на потребителя да превключвате между екраните на календара, активирайте тази опция и изберете вижданията, които искате да се показват. ",
    "Main": "Основен",
    "Localize": "Локализирам",
    "Settings": "Настройки",
    "Layouts": "Формати",
    "Advanced": "Напреднал",
    "Design": "Дизайн",
    "Support": "Поддържа",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Всички локални настройки са (автоматично) въз основа на вашия език. Ако вашият език е в списъка, няма нужда да персонализирате този раздел.",
    "Date Format": "Формат на датата",
    "Time Format": "Времеви формат",
    "Text Direction": "Посочване на текст",
    "Left to Right": "Отляво надясно",
    "Right to Left": "От дясно на ляво",
    "Week Starts On": "Седмицата започва на",
    "Agenda Style": "Стил на дневния ред:",
    "Classic": "Класик",
    "Modern": "Mодерен",
    "Agenda Header": "Заглавие на дневния ред",
    "Upcoming Events": "Предстоящи събития",
    "Agenda Event Limit": "Ограничение на събитието в дневния ред",
    "Upgrade now and get a lot more features and enjoy your APP in full!": "Надстройте сега и получете много повече функции и се наслаждавайте изцяло на приложението си !",
    "Upgrade Now": "Надстройка сега:",
    "Hosting events that last all day? This lets you show them on your calendar.":"Хостинг събития, които продължават цял ​​ден? Това ви позволява да ги показвате в календара си.",
    "24 hours":"24 часа",
    "Sun": "Неделя",
    "Mon": "Понед",
    "Sat": "Събота",
    "Default": "По подразбиране",
    "Select custom design style for your calendar.": "Изберете персонализиран стил на дизайн за вашия календар.",
    "Style":"Стил",
    "Styles and Colors": "Стилове и цветове",
    "Calendar Name":"Име на календара",
    "Write your Calendar name here":"Напишете името на календара си тук",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"Това не се вижда от вашите потребители. Задайте имена, за да разграничите вашите календари, когато използвате функцията Boom Calendar Sync.",
    "General Info" : "Обща информация",
    "Venue" : "Място на провеждане",
    "Organizer"  : "Организатор"
}

export default bg;
