let cs = {
    "Language": "Jazyk",
    "Show Time Zone": "Zobrazit časové pásmo",
    "Custom Local Settings": "Vlastní místní nastavení",
    "Add and showcase events on your site using a beautiful calendar.": "Přidejte a předveďte události na svém webu pomocí krásného kalendáře . ",
    "Week Days": "Týdenní dny",
    "Manage Events": "Spravovat události",
    "General": "Všeobecné",
    "Layout Picker": "Výběr rozvržení",
    "Month": "Měsíc",
    "Monthly": "Měsíční",
    "Week": "Týden",
    "Weekly": "Týdně",
    "Day": "Den",
    "Daily": "Denně",
    "Agenda": "Denní program",
    "Navigation Buttons": "Navigační tlačítka",
    "Today": "Dnes",
    "Week numbers": "Týdenní čísla",
    "Include Weekends": "Zahrnout víkendy",
    "All-day": "Celý den",
    "All Day": "Celý den",
    "Label": "Označení",
    "Fit to Height": "Přizpůsobit výšce",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "Chcete-li nastavit App proporce manully tuto možnost zakázat a velikost kalendáře v editoru. ",
    "Default Layout": "Výchozí rozvržení",
    "Monthly view": "Měsíční zobrazení",
    "Weekly and Daily view": "Týdenní a denní zobrazení",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Návštěvníkům můžete poskytnout konzistentnější zážitek tím, že budete zobrazovat stejný počet týdnů ( 6) najednou.",
    "Fixed Weekly Layout": "Opraveno týdenní rozložení",
    "back": " zpět ",
    "Row": "Řádek",
    "Hours in Weekly View": "Hodiny v týdenním zobrazení",
    "Hours in Daily View": "Hodiny v denním zobrazení",
    "Start": "Start",
    "End": "Konec",
    "At This Hour": "V tuto hodinu",
    "Add to": "Přidat do",
    "Button": "Tlačítko",
    "Buttons": "Tlačítka",
    "Sunday": "Neděle",
    "Monday": "Pondělí",
    "Tuesday": "Úterý",
    "Wednesday": "Středa",
    "Thursday": " Čtvrtek ",
    "Friday": "Pátek",
    "Saturday": "Sobota",
    "Default Date": "Výchozí datum",
    "year": " rok ",
    "month": " měsíc ",
    "days": " dny ",
    "ago": " před ",
    "ahead": " dopředu ",
    "Yesterday": "Včera",
    "Today": "Dnes",
    "Tomorrow": "Zítra",
    "Custom": "Zvyk",
    "Set Daily Rows Limit": "Nastavit denní limit řádků",
    "Set Proportions": "Nastavit proporce",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Povolit návštěvníkovi přidat událost do místních Calnedars , Google, Yahoo, Outlook, ICalendar . ",
    "Container": "Kontejner",
    "Background": "Pozadí",
    "Container Background": "Pozadí kontejneru",
    "Container Borders": "Hranice kontejneru",
    "Calendar": "Kalendář",
    "Event Info Tooltip": "Popis informací o události",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "Když se lidé vznášejí nad událostí, uvidí všechny informace o ní v popisku. ",
    "Event Info Window": "Okno s informacemi o události",
    "This is the full information window that opens when someone clicks on the event.": "Toto je úplné informační okno, které se otevře, když někdo klikne na událost. ",
    "Use Gradient": "Použít přechod",
    "Vertical": "Vertikální",
    "Horizontal": "Horizontální",
    "First": "První",
    "Second": "Druhý",
    "diagonal": " diagonální ",
    "Radial": "Radiální",
    "Select option": "Vyberte možnost",
    "Solid": "Pevný",
    "Dotted": "Tečkovaný",
    "Dashed": "Dashed",
    "Double": "Dvojnásobek",
    "Border Radius": "Hraniční poloměr",
    "Padding": "Padding",
    "Date Header": "Záhlaví data",
    "Event Default Color": "Výchozí barva události",
    "Days of Week": "Dny v týdnu",
    "Days of Week Background": "Dny v týdnu na pozadí",
    "Date": "Datum",
    "Event Title": "Název události",
    "Highlight today": "Zvýrazněte dnes",
    "Highlight Color": "Zvýraznit barvu",
    "Hide": "Skrýt",
    "Calendar Border Color": "Barva okraje kalendáře",
    "Calendar Border Width": "Šířka okraje kalendáře",
    "Calendar Border Style": "Styl okraje kalendáře",
    "Font Color": "Barva fontu",
    "Event Background": "Pozadí události",
    "Card Date Color": "Barva data karty",
    "Title Font": "Název písma",
    "Date Font": "Date Font",
    "Description Font": "Popisové písmo",
    "Button Background": "Pozadí tlačítka",
    "Button Text": "Text tlačítka",
    "Border Color": "Border Color",
    "Border Width": "Šířka okraje",
    "Border Type": "Typ ohraničení",
    "Title": "Titul",
    "Description": "Popis",
    "Background Color": "Barva pozadí",
    "Divider": "Oddělovač",
    "Event Details Font": "Písmo podrobností události",
    "Website Link Color": "Barva odkazu na web",
    "Developer Info": "Informace pro vývojáře",
    "User Guide": "Uživatelská příručka",
    "Support e-mail": "Podpora e-mailu",
    "Our Website": "Náš web",
    "App Review": "Recenze aplikace",
    "Enjoying App? Leave us a review in the App Market.": "Užíváte si aplikaci? Nechte nás na App App recenzi. ",
    "Review Us": "Recenze nás",
    "Connect With Us": "Spojit se s námi",
    "What's your email?": "Jaký je váš e-mail? ",
    "Invalid email address!": "Neplatná e-mailová adresa! ",
    "Comments": "Komentáře",
    "We'd love to hear from you. Send us a message.": "Rádi bychom od vás slyšeli. Pošlete nám zprávu. ",
    "Message must be at least 5 characters long": "Zpráva musí obsahovat alespoň 5 znaků",
    "Send": "Poslat",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Pokud chcete uživateli umožnit přepínání mezi zobrazeními kalendáře, aktivujte tuto možnost a zvolte pohledy, které chcete zobrazit. ",
    "Main": "Hlavní",
    "Localize": "Lokalizovat",
    "Settings": "Nastavení",
    "Layouts": "Rozložení",
    "Advanced": "Pokročilý",
    "Design": "Design",
    "Support": "Podpěra, podpora",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Všechna místní nastavení jsou (automaticky) založena na vašem jazyce. Pokud je váš jazyk na seznamu, není třeba tuto sekci upravovat.",
    "Date Format": "Datový formát",
    "Time Format": "Časový formát",
    "Text Direction": "Směr textu",
    "Left to Right": "Zleva do prava",
    "Right to Left": "Zprava doleva",
    "Week Starts On": "Začátek týdne",
    "Agenda Style": "Agenda Styl",
    "Classic":"Klasický",
    "Modern":"Moderní",
    "Agenda Header":"Hlavička agendy",
    "Upcoming Events":"Připravované akce",
    "Agenda Event Limit": "Agenda Event Limit",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"Upgradujte nyní a získejte mnohem více funkcí a užijte si svoji aplikaci v plném rozsahu!",
    "Upgrade Now":"Vylepšit nyní",
    "Hosting events that last all day? This lets you show them on your calendar.":"Hostit událostí, které trvají celý den? To vám umožní zobrazit je v kalendáři.",
    "24 hours":"24 hodin",
    "Sat": "Sobota",
    "Sun": "Neděle",
    "Mon": "Pondělí",
    "Default": "Výchozí",
    "Select custom design style for your calendar.": "Vyberte vlastní styl designu pro svůj kalendář.",
    "Style": "Styl",
    "Styles and Colors": "Styly a barvy",
    "Calendar Name":"Název kalendáře",
    "Write your Calendar name here":"Sem napište své jméno kalendáře",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"Toto není pro vaše uživatele viditelné. Pokud používáte funkci synchronizace kalendáře Boom, nastavte názvy tak, aby se vaše kalendáře odlišovaly.",
    "General Info" : "Obecné informace",
    "Venue" : "Místo",
    "Organizer"  : "Organizátor"
};

export default cs;
