let el = {
    "Language": "Γλώσσα",
    "Show Time Zone": "Εμφάνιση ζώνης ώρας",
    "Custom Local Settings": "Προσαρμοσμένες τοπικές ρυθμίσεις",
    "Add and showcase events on your site using a beautiful calendar.": "Προσθήκη και εμφάνιση συμβάντων στον ιστότοπό σας χρησιμοποιώντας ένα όμορφο ημερολόγιο . ",
    "Week Days": "Εβδομάδες ημέρες",
    "Manage Events": "Διαχείριση εκδηλώσεων",
    "General": "Γενικός",
    "Layout Picker": "Επιλογή διαρρυθμίσεων",
    "Month": "Μήνας",
    "Monthly": "Μηνιαίος",
    "Week": "Εβδομάδα",
    "Weekly": "Εβδομαδιαίος",
    "Day": "Ημέρα",
    "Daily": "Καθημερινά",
    "Agenda": "Ημερήσια διάταξη",
    "Navigation Buttons": "Κουμπιά πλοήγησης",
    "Today": "Σήμερα",
    "Week numbers": "Αριθμοί εβδομάδας",
    "Include Weekends": "Συμπερίληψη Σαββατοκύριακου",
    "All-day": "Ολη μέρα",
    "All Day": "Ολη μέρα",
    "Label": "Επιγραφή",
    "Fit to Height": "Προσαρμογή σε Ύψος",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "Για να ρυθμίσετε τις αναλογίες εφαρμογών, απενεργοποιήστε χειροκίνητα αυτή την επιλογή και αλλάξτε το μέγεθος του Ημερολογίου στον επεξεργαστή.",
    "Default Layout": "Προεπιλεγμένη διάταξη",
    "Monthly view": "Μηνιαία προβολή",
    "Weekly and Daily view": "Εβδομαδιαία και ημερήσια προβολή",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Μπορείτε να δώσετε στους επισκέπτες μια πιο συνεπή εμπειρία δείχνοντας τον ίδιο αριθμό εβδομάδων ( 6) κάθε φορά.",
    "Fixed Weekly Layout": "Σταθερή εβδομαδιαία διάταξη",
    "back": " πίσω ",
    "Row": "Σειρά",
    "Hours in Weekly View": "Ώρες στην εβδομαδιαία προβολή",
    "Hours in Daily View": "Ώρες στην καθημερινή προβολή",
    "Start": "Αρχή",
    "End": "Τέλος",
    "At This Hour": "Σε αυτήν την ώρα",
    "Add to": "Προσθήκη στο",
    "Button": "Κουμπί",
    "Buttons": "Κουμπιά",
    "Sunday": "Κυριακή",
    "Monday": "Δευτέρα",
    "Tuesday": "Τρίτη",
    "Wednesday": "Τετάρτη",
    "Thursday": " Πέμπτη ",
    "Friday": "Παρασκευή",
    "Saturday": "Σάββατο",
    "Default Date": "Ημερομηνία προεπιλογής",
    "year": " έτος ",
    "month": " μήνας ",
    "days": " ημέρες ",
    "ago": " πριν ",
    "ahead": " μπροστά ",
    "Yesterday": "Εχθές",
    "Today": "Σήμερα",
    "Tomorrow": "Αύριο",
    "Custom": "Εθιμο",
    "Set Daily Rows Limit": "Ορισμός ημερήσιων ορίων γραμμών",
    "Set Proportions": "Ρύθμιση αναλογιών",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Επιτρέψτε στον επισκέπτη να προσθέσει συμβάν στο τοπικό Calnedars , Google, Yahoo, Outlook, ICalendar . ",
    "Container": "Δοχείο",
    "Background": "Ιστορικό",
    "Container Background": "Ιστορικό κοντέινερ",
    "Container Borders": "Περιοχή δοχείων",
    "Calendar": "Ημερολόγιο",
    "Event Info Tooltip": "Πληροφορίες συμβάντος συμβάντων συμβάντων",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "Όταν οι άνθρωποι αιωρούνται πάνω από ένα συμβάν, θα δουν όλες τις πληροφορίες σχετικά με αυτό σε μια επεξήγηση εργαλείου ",
    "Event Info Window": "Παράθυρο πληροφοριών συμβάντος",
    "This is the full information window that opens when someone clicks on the event.": "Αυτό είναι το πλήρες παράθυρο πληροφοριών που ανοίγει όταν κάποιος κάνει κλικ στο συμβάν. ",
    "Use Gradient": "Χρήση κλίσης",
    "Vertical": "Κατακόρυφος",
    "Horizontal": "Οριζόντιος",
    "First": "Πρώτα",
    "Second": "Δεύτερος",
    "diagonal": " διαγώνιος ",
    "Radial": "Ακτινικός",
    "Select option": "Επιλογή επιλογής",
    "Solid": "Στερεός",
    "Dotted": "Διάσπαρτος",
    "Dashed": "Διακεκομμένη",
    "Double": "Διπλό",
    "Border Radius": "Ακτίνα ορίου",
    "Padding": "Υλικό παραγεμίσματος",
    "Date Header": "Κεφαλίδα ημερομηνίας",
    "Event Default Color": "Χρώμα προεπιλογής συμβάντος",
    "Days of Week": "Ημέρες της εβδομάδας",
    "Days of Week Background": "Ημέρες της εβδομάδας",
    "Date": "Ημερομηνία",
    "Event Title": "Τίτλος συμβάντος",
    "Highlight today": "Επισημάνετε σήμερα",
    "Highlight Color": "Επισημάνετε χρώμα",
    "Hide": "Κρύβω",
    "Calendar Border Color": "Χρώμα περιθωρίου ημερολογίου",
    "Calendar Border Width": "Πλάτος περιθωρίου ημερολογίου",
    "Calendar Border Style": "Στυλ γραμμής πλαισίου",
    "Font Color": "Χρώμα γραμματοσειράς",
    "Event Background": "Ιστορικό συμβάντων",
    "Card Date Color": "Χρόνος ημερομηνίας κάρτας",
    "Title Font": "Γραμματοσειρά τίτλου",
    "Date Font": "Ημερομηνία γραμματοσειράς",
    "Description Font": "Γραμματοσειρά περιγραφής",
    "Button Background": "Κουμπί Background",
    "Button Text": "Κείμενο κουμπιού",
    "Border Color": "Χρώμα πλαισίου",
    "Border Width": "Πλάτος περιθωρίου",
    "Border Type": "Τύπος περιγράμματος",
    "Title": "Τίτλος",
    "Description": "Περιγραφή",
    "Background Color": "Χρώμα του φόντου",
    "Divider": "Διαιρών",
    "Event Details Font": "Λεπτομέρειες συμβάντος γραμματοσειράς",
    "Website Link Color": "Χρώμα συνδέσμου ιστότοπου",
    "Developer Info": "Πληροφορίες προγραμματιστή",
    "User Guide": "ΟΔΗΓΟΣ ΧΡΗΣΤΗ",
    "Support e-mail": "Υποστήριξη",
    "Our Website": "Η ιστοσελίδα μας",
    "App Review": "Ενημέρωση εφαρμογής",
    "Enjoying App? Leave us a review in the App Market.": "Απολαύστε την εφαρμογή; Αφήστε μας μια κριτική στην αγορά εφαρμογών. ",
    "Review Us": "Εξετάστε μας",
    "Connect With Us": "Σύνδεση με εμάς",
    "What's your email?": "Ποιο είναι το email σας; ",
    "Invalid email address!": "Μη έγκυρη διεύθυνση ηλεκτρονικού ταχυδρομείου! ",
    "Comments": "Σχόλια",
    "We'd love to hear from you. Send us a message.": "Θα θέλαμε να σας ακούσουμε. Στείλτε μας ένα μήνυμα. ",
    "Message must be at least 5 characters long": "Μήνυμα πρέπει να έχει μήκος τουλάχιστον 5 χαρακτήρων",
    "Send": "Στείλετε",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Αν θέλετε να επιτρέψετε στο χρήστη να αλλάξει τις προβολές ημερολογίου, ενεργοποιήστε αυτήν την επιλογή και επιλέξτε τις προβολές που θέλετε να εμφανίσετε.",
    "Main": "Κύριος",
    "Localize": "Εντοπίζω",
    "Settings": "Ρυθμίσεις",
    "Layouts": "Διατάξεις",
    "Advanced": "Προχωρημένος",
    "Design": "Σχέδιο",
    "Support": "Υποστήριξη",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Όλες οι τοπικές ρυθμίσεις βασίζονται (αυτόματα) στη γλώσσα σας. Εάν η γλώσσα σας βρίσκεται στη λίστα, δεν χρειάζεται να προσαρμόσετε αυτήν την ενότητα.",
    "Date Format":"Μορφή ημερομηνίας",
    "Time Format":"Μορφή ώρας",
    "Text Direction":"Κατεύθυνση κειμένου",
    "Left to Right":"Από αριστερά προς τα δεξιά",
    "Right to Left":"Δεξιά προς τα αριστερά",
    "Week Starts On":"Εβδομάδα ξεκινά",
    "Agenda Style":"Ατζέντα στυλ",
    "Classic":"Κλασσικός",
    "Modern":"Μοντέρνο",
    "Agenda Header":"Ημερολόγιο ημερήσιας διάταξης",
    "Upcoming Events":"Επερχόμενα γεγονότα",
    "Agenda Event Limit":"Όριο συμβάντων ημερήσιας διάταξης",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"Αναβαθμίστε τώρα και αποκτήστε περισσότερα χαρακτηριστικά και απολαύστε το APP σας πλήρως!",
    "Upgrade Now":"Αναβάθμισε τώρα",
    "Hosting events that last all day? This lets you show them on your calendar.":
    "Φιλοξενία γεγονότων που διαρκούν όλη την ημέρα; Αυτό σας επιτρέπει να τα εμφανίσετε στο ημερολόγιό σας",
    "24 hours":"24 ώρες",
    "Sun": "Κυριακή",
    "Mon": "Δευτέρα",
    "Sat": "Σάββατο",
    "Default": "Προκαθορισμένο",
    "Select custom design style for your calendar.":  "Επιλέξτε το προσαρμοσμένο στυλ σχεδιασμού για το ημερολόγιό σας.",
    "Style": "Στυλ",
    "Styles and Colors": "Στυλ και χρώματα",
    "Calendar Name":"Όνομα ημερολογίου",
    "Write your Calendar name here":"Γράψτε το όνομα του ημερολογίου σας εδώ",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"Αυτό δεν είναι ορατό στους χρήστες σας. Ορίστε ονόματα για να διαφοροποιήσετε τα ημερολόγιά σας όταν χρησιμοποιείτε τη λειτουργία Συγχρονισμός ημερολογίου Boom.",
    "General Info" : "Γενικές πληροφορίες",
    "Venue" : "Τόπος συναντήσεως",
    "Organizer"  : "Διοργανωτής"

};

export default el;
