let en = {
    "Language": "Language",
    "Show Time Zone": "Show Time Zone",
    "Custom Local Settings": "Custom Local Settings",
    "Add and showcase events on your site using a beautiful calendar.": 'Add and showcase events on your site using a beautiful calendar.',
    "Week Days": 'Week Days',
    "Manage Events": "Manage Events",
    "General": "General",
    "Layout Picker": "Layout Picker",
    "Month": "Month",
    "Monthly": "Monthly",
    "Week": "Week",
    "Weekly": "Weekly",
    "Day": "Day",
    "Daily": "Daily",
    "Agenda": "Agenda",
    "Navigation Buttons": "Navigation Buttons",
    "Today": "Today",
    "Week numbers": "Week numbers",
    "Include Weekends": "Include Weekends",
    "All-day": "All-day",
    "All Day": "All day",
    "Label": "Label",
    "Fit to Height": "Fit to Height",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "To set App proportions manually disable this option and resize Calendar in Editor.",
    "Default Layout": "Default Layout",
    "Monthly view": "Monthly view",
    "Weekly and Daily view": "Weekly and Daily view",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.",
    "Fixed Weekly Layout": "Fixed Weekly Layout",
    "back": "back",
    "Row": "Row",
    "Hours in Weekly View": "Hours in Weekly View",
    "Hours in Daily View": "Hours in Daily View",
    "Start": "Start",
    "End": "End",
    "At This Hour": "At This Hour",
    "Add to": "Add to",
    "Button": "Button",
    "Buttons": "Buttons",
    "Sunday": "Sunday",
    "Monday": "Monday",
    "Tuesday": "Tuesday",
    "Wednesday": "Wednesday",
    "Thursday": "Thursday",
    "Friday": "Friday",
    "Saturday": "Saturday",
    "Default Date": "Default Date",
    "year": "year",
    "month": "month",
    "days": "days",
    "ago": "ago",
    "ahead": "ahead",
    "Yesterday": "Yesterday",
    "Today": "Today",
    "Tomorrow": "Tomorrow",
    "Custom": "Custom",
    "Set Daily Rows Limit": "Set Daily Rows Limit",
    "Set Proportions": "Set Proportions",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Allow visitor to add event to local Calendars: Google, Yahoo, Outlook, ICalendar.",
    "Container": "Container",
    "Background": "Background",
    "Container Background": "Container Background",
    "Container Borders": "Container Borders",
    "Calendar": "Calendar",
    "Event Info Tooltip": "Event Info Tooltip",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "When people hover over an event they’ll see all the info about it in a tooltip.",
    "Event Info Window": "Event Info Window",
    "This is the full information window that opens when someone clicks on the event.": "This is the full information window that opens when someone clicks on the event.",
    "Use Gradient": "Use Gradient",
    "Vertical": "Vertical",
    "Horizontal": "Horizontal",
    "First": "First",
    "Second": "Second",
    "diagonal": "diagonal",
    "Radial": "Radial",
    "Select option": "Select option",
    "Solid": "Solid",
    "Dotted": "Dotted",
    "Dashed": "Dashed",
    "Double": "Double",
    "Border Radius": "Border Radius",
    "Padding": "Padding",
    "Date Header": "Date Header",
    "Event Default Color": "Event Default Color",
    "Days of Week": "Days of Week",
    "Days of Week Background": "Days of Week Background",
    "Date": "Date",
    "Event Title": "Event Title",
    "Highlight today": "Highlight today",
    "Highlight Color": "Highlight Color",
    "Hide": "Hide",
    "Calendar Border Color": "Calendar Border Color",
    "Calendar Border Width": "Calendar Border Width",
    "Calendar Border Style": "Calendar Border Style",
    "Font Color": "Font Color",
    "Event Background": "Event Background",
    "Card Date Color": "Card Date Color",
    "Title Font": "Title Font",
    "Date Font": "Date Font",
    "Description Font": "Description Font",
    "Button Background": "Button Background",
    "Button Text": "Button Text",
    "Border Color": "Border Color",
    "Border Width": "Border Width",
    "Border Type": "Border Type",
    "Title": "Title",
    "Description": "Description",
    "Background Color": "Background Color",
    "Divider": "Divider",
    "Event Details Font": "Event Details Font",
    "Website Link Color": "Website Link Color",
    "Developer Info": "Developer Info",
    "User Guide": "User Guide",
    "Support e-mail": "Support e-mail",
    "Our Website": "Our Website",
    "App Review": "App Review",
    "Enjoying App? Leave us a review in the App Market.": "Enjoying App? Leave us a review in the App Market.",
    "Review Us": "Review Us",
    "Connect With Us": "Connect With Us",
    "What's your email?": "What's your email?",
    "Invalid email address!": "Invalid email address!",
    "Comments": "Comments",
    "We'd love to hear from you. Send us a message.": "We'd love to hear from you. Send us a message.",
    "Message must be at least 5 characters long": "Message must be at least 5 characters long",
    "Send": "Send",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.",
    "Main": "Main",
    "Localize": "Localize",
    "Settings": "Settings",
    "Layouts": "Layouts",
    "Advanced": "Advanced",
    "Design": "Design",
    "Support": "Support",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.",
    "Date Format":"Date Format",
    "Time Format":"Time Format",
    "Text Direction":"Text Direction",
    "Left to Right":"Left to Right",
    "Right to Left":"Right to Left",
    "Week Starts On":"Week Starts On",
    "Agenda Style":"Agenda Style",
    "Classic":"Classic",
    "Modern":"Modern",
    "Agenda Header": "Agenda Header",
    "Upcoming Events":"Upcoming Events",
    "Agenda Event Limit":"Agenda Event Limit",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"Upgrade now and get a lot more features and enjoy your APP in full!",
    "Upgrade Now":"Upgrade Now",
    "Hosting events that last all day? This lets you show them on your calendar.":"Hosting events that last all day? This lets you show them on your calendar.",
    "24 hours":"24 hours",
    "Sun": "Sun",
    "Mon": "Mon",
    "Sat": "Sat",
    "Default": "Default",
    "Style":"Style",
    "Calendar Name":"Calendar Name",
    "Write your Calendar name here":"Write your Calendar name here",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.",
    "General Info" : "General Info",
    "Venue" : "Venue",
    "Organizer"  : "Organizer"
}

export default en;
