let es = {
    "Language": "Idioma",
    "Show Time Zone": "Mostrar zona horaria",
    "Custom Local Settings": "Configuración local personalizada",
    "Add and showcase events on your site using a beautiful calendar.": "Agregue y muestre eventos en su sitio usando un calendario hermoso",
    "Week Days": "Días de la semana",
    "Manage Events": "Administrar eventos",
    "General": "General",
    "Layout Picker": "Selector de diseño",
    "Month": "Mes",
    "Monthly": "Mensual",
    "Week": "Semana",
    "Weekly": "Semanal",
    "Day": "Día",
    "Daily": "Diario",
    "Agenda": "Agenda",
    "Navigation Buttons": "Botones de navegacion",
    "Today": "Hoy",
    "Week numbers": "Números semanales",
    "Include Weekends": "Incluir fines de semana",
    "All-day": "Todo el dia",
    "All Day": "Todo el dia",
    "Label": "Etiqueta",
    "Fit to Height": "Ajustar a la altura",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "Para establecer proporciones de aplicaciones, desactive esta opción y cambie el tamaño del Calendario en el Editor",
    "Default Layout": "Diseño predeterminado",
    "Monthly view": "Vista mensual",
    "Weekly and Daily view": "Vista semanal y diaria",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Puede brindar a los visitantes una experiencia más consistente mostrando la misma cantidad de semanas (6) a la vez",
    "Fixed Weekly Layout": "Diseño semanal fijo",
    "back": "espalda",
    "Row": "Fila",
    "Hours in Weekly View": "Horas en vista semanal",
    "Hours in Daily View": "Horas en la vista diaria",
    "Start": "Comienzo",
    "End": "Final",
    "At This Hour": "A esta hora",
    "Add to": "Añadir",
    "Button": "Botón",
    "Buttons": "Botones",
    "Sunday": "Domingo",
    "Monday": "Lunes",
    "Tuesday": "Martes",
    "Wednesday": "Miércoles",
    "Thursday": "Jueves",
    "Friday": "Viernes",
    "Saturday": "Sábado",
    "Default Date": "Fecha predeterminada",
    "year": "año",
    "month": "mes",
    "days": "dias",
    "ago": "hace",
    "ahead": "adelante",
    "Yesterday": "Ayer",
    "Today": "Hoy",
    "Tomorrow": "Mañana",
    "Custom": "Personalizado",
    "Set Daily Rows Limit": "Establecer límite diario de filas",
    "Set Proportions": "Establecer proporciones",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Permitir al visitante agregar un evento a los Calnedars locales, Google, Yahoo, Outlook, ICalendar",
    "Container": "Envase",
    "Background": "Fondo",
    "Container Background": "Fondo del contenedor",
    "Container Borders": "Fronteras de contenedores",
    "Calendar": "Calendario",
    "Event Info Tooltip": "Información sobre herramientas de información del evento",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "Cuando las personas se ciernen sobre un evento, verán toda la información al respecto en una descripción emergente",
    "Event Info Window": "Ventana de información del evento",
    "This is the full information window that opens when someone clicks on the event.": "Esta es la ventana de información completa que se abre cuando alguien hace clic en el evento",
    "Use Gradient": "Usar degradado",
    "Vertical": "Vertical",
    "Horizontal": "Horizontal",
    "First": "Primero",
    "Second": "Segundo",
    "diagonal": "diagonal",
    "Radial": "Radial",
    "Select option": "Seleccionar opción",
    "Solid": "Sólido",
    "Dotted": "Punteado",
    "Dashed": "Rayado",
    "Double": "Doble",
    "Border Radius": "Radio de borde",
    "Padding": "Relleno",
    "Date Header": "Encabezado de fecha",
    "Event Default Color": "Color predeterminado del evento",
    "Days of Week": "Días de la semana",
    "Days of Week Background": "Fondo de días de la semana",
    "Date": "Fecha",
    "Event Title": "Título del evento",
    "Highlight today": "Destacar hoy",
    "Highlight Color": "Color de resaltado",
    "Hide": "Esconder",
    "Calendar Border Color": "Color del borde del calendario",
    "Calendar Border Width": "Ancho del borde del calendario",
    "Calendar Border Style": "Estilo de borde de calendario",
    "Font Color": "Color de fuente",
    "Event Background": "Antecedentes del evento",
    "Card Date Color": "Color de la fecha de la tarjeta",
    "Title Font": "Fuente del titulo",
    "Date Font": "Fuente de fecha",
    "Description Font": "Fuente de descripción",
    "Button Background": "Fondo del botón",
    "Button Text": "Botón de texto",
    "Border Color": "Color del borde",
    "Border Width": "Ancho del borde",
    "Border Type": "Tipo de borde",
    "Title": "Título",
    "Description": "Descripción",
    "Background Color": "Color de fondo",
    "Divider": "Divisor",
    "Event Details Font": "Fuente de detalles del evento",
    "Website Link Color": "Color del enlace del sitio web",
    "Developer Info": "Información del desarrollador",
    "User Guide": "Guía del usuario",
    "Support e-mail": "Correo electrónico de soporte",
    "Our Website": "Nuestra página web",
    "App Review": "Revisión de la aplicación",
    "Enjoying App? Leave us a review in the App Market.": "¿Disfrutando de la aplicación? Déjanos un comentario en el App Market",
    "Review Us": "Revisarnos",
    "Connect With Us": "Conectate con nosotros",
    "What's your email?": "¿Cuál es tu correo electrónico?",
    "Invalid email address!": "¡Dirección de correo electrónico no válida!",
    "Comments": "Comentarios",
    "We'd love to hear from you. Send us a message.": "Nos encantaría saber de usted. Envíenos un mensaje",
    "Message must be at least 5 characters long": "El mensaje debe tener al menos 5 caracteres",
    "Send": "Enviar",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Si desea permitir que el usuario cambie entre vistas de calendario, habilite esta opción y elija las vistas que desea mostrar",
    "Main": "Principal",
    "Localize": "Localizar",
    "Settings": "Configuraciones",
    "Layouts": "Diseños",
    "Advanced": "Avanzado",
    "Design": "Diseño",
    "Support": "Apoyo",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Todas las configuraciones locales se basan (automáticamente) en su idioma. Si su idioma está en la lista, no es necesario personalizar esta sección.",
    "Date Format":"Formato de fecha",
    "Time Format":"Formato de tiempo",
    "Text Direction":"Dirección del texto",
    "Left to Right":"De izquierda a derecha",
    "Right to Left":"De derecha a izquierda",
    "Week Starts On":"La semana empieza el",
    "Agenda Style":"Estilo de agenda",
    "Classic":"Clásico",
    "Modern":"Moderno",
    "Agenda Header":"Encabezado de agenda",
    "Upcoming Events":"Próximos Eventos",
    "Agenda Event Limit":"Límite de evento de agenda",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"¡Actualiza ahora y obtén muchas más funciones y disfruta de tu APLICACIÓN por completo!",
    "Upgrade Now":"Actualizar ahora",
    "Hosting events that last all day? This lets you show them on your calendar.":"¿Organizar eventos que duran todo el día? Esto te permite mostrarlos en tu calendario",
    "24 hours":"24 horas",
    "Sat": "Sáb",
    "Sun": "Dom",
    "Mon": "Lun",
    "Default": "Defecto",
    "Select custom design style for your calendar.": "Seleccione un estilo de diseño personalizado para su calendario.",
    "Style": "Estilo",
    "Styles and Colors": "Estilos y colores",
    "Calendar Name":"Nombre del calendario",
    "Write your Calendar name here":"Escriba su nombre de calendario aquí",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"Esto no es visible para sus usuarios. Establezca nombres para diferenciar sus calendarios cuando use la función Boom Calendar Sync.",
    "General Info" : "Γενικές πληροφορίες",
    "Venue" : "Lugar de eventos",
    "Organizer"  : "Organizador"
}

export default es;
