let fr = {
    "Language": "La langue",
    "Show Time Zone": "Afficher le fuseau horaire",
    "Custom Local Settings": "Paramètres locaux personnalisés",
    "Add and showcase events on your site using a beautiful calendar.": "Ajoutez et présentez des événements sur votre site en utilisant un beau calendrier . ",
    "Week Days": "Jours de la semaine",
    "Manage Events": "Gérer les événements",
    "General": "Général",
    "Layout Picker": "Layout Picker",
    "Month": "Mois",
    "Monthly": "Mensuel",
    "Week": "La semaine",
    "Weekly": "Hebdomadaire",
    "Day": "Journée",
    "Daily": "Du quotidien",
    "Agenda": "Ordre du jour",
    "Navigation Buttons": "Boutons de navigation",
    "Today": "Aujourd'hui",
    "Week numbers": "Numéros de semaine",
    "Include Weekends": "Inclure les week-ends",
    "All-day": "Toute la journée",
    "All Day": "Toute la journée",
    "Label": "Étiquette",
    "Fit to Height": "Ajuster à la hauteur",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "Pour définir les proportions de l'application, désactivez manuellement cette option et redimensionnez le calendrier dans l'éditeur.",
    "Default Layout": "Mise en page par défaut",
    "Monthly view": "Vue mensuelle",
    "Weekly and Daily view": "Vue hebdomadaire et quotidienne",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Vous pouvez offrir aux visiteurs une expérience plus cohérente en affichant le même nombre de semaines (6) à la fois.",
    "Fixed Weekly Layout": "Mise en page hebdomadaire fixe",
    "back": "retour",
    "Row": "Rangée",
    "Hours in Weekly View": "Heures en affichage hebdomadaire",
    "Hours in Daily View": "Heures en affichage quotidien",
    "Start": "Début",
    "End": "Fin",
    "At This Hour": "À cette heure",
    "Add to": "Ajouter à",
    "Button": "Bouton",
    "Buttons": "Boutons",
    "Sunday": "Dimanche",
    "Monday": "Lundi",
    "Tuesday": "Mardi",
    "Wednesday": "Mercredi",
    "Thursday": "Mardi",
    "Friday": "Vendredi",
    "Saturday": "Samedi",
    "Default Date": "Date par défaut",
    "year": "année",
    "month": "mois",
    "days": "journées",
    "ago": "depuis",
    "ahead": "devant",
    "Yesterday": "Hier",
    "Tomorrow": "Demain",
    "Custom": "Douane",
    "Set Daily Rows Limit": "Définir la limite quotidienne de lignes",
    "Set Proportions": "Définir les proportions",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": " Autoriser un visiteur à ajouter un événement aux journaux locaux, Google, Yahoo, Outlook, ICalendar.",
    "Container": "Récipient",
    "Background": "Contexte",
    "Container Background": "Contexte du conteneur",
    "Container Borders": "Frontières de conteneurs",
    "Calendar": "Calendrier",
    "Event Info Tooltip": "Info sur l'événement",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "Lorsque les personnes survolent un événement, elles voient toutes les informations à ce sujet dans une info-bulle.",
    "Event Info Window": "Fenêtre d'informations sur l'événement",
    "This is the full information window that opens when someone clicks on the event.": "Il s'agit de la fenêtre d'informations complètes qui s'ouvre lorsque quelqu'un clique sur l'événement.",
    "Use Gradient": "Utiliser le dégradé",
    "Vertical": "Verticale",
    "Horizontal": "Horizontal",
    "First": "Premier",
    "Second": "Seconde",
    "diagonal": "diagonale",
    "Radial": "Radial",
    "Select option": "Choisir une option",
    "Solid": "Solide",
    "Dotted": "À pois",
    "Dashed": "Dashed",
    "Double": "Doub le",
    "Border Radius": "Rayon de la frontière",
    "Padding": "Rembourrage",
    "Date Header": "Date Header",
    "Event Default Color": "Couleur par défaut de l'événement",
    "Days of Week": "Jours de la semaine",
    "Days of Week Background": "Contexte des jours de la semaine",
    "Date": "Rendez-vous amoureux",
    "Event Title": "Titre de l'événement",
    "Highlight today": "Mettez en valeur aujourd'hui",
    "Highlight Color": "Couleur de surbrillance",
    "Hide": "Cacher",
    "Calendar Border Color": "Couleur de la bordure du calendrier",
    "Calendar Border Width": "Largeur de la bordure du calendrier",
    "Calendar Border Style": "Style de bordure de calendrier",
    "Font Color": "Couleur de la police",
    "Event Background": "Contexte de l'événement",
    "Card Date Color": "Couleur de la date de la carte",
    "Title Font": "Police de titre",
    "Date Font": "Date Police",
    "Description Font": "Description Font",
    "Button Background": "Arrière-plan du bouton",
    "Button Text": "Texte du bouton",
    "Border Color": "Couleur de la bordure",
    "Border Width": "Largeur de la bordure",
    "Border Type": "Type de bordure",
    "Title": "Titre",
    "Description": "La description",
    "Background Color": "Couleur de fond",
    "Divider": "Diviseur",
    "Event Details Font": " Police des détails de l'événement",
    "Website Link Color": "Couleur du lien de site Web",
    "Developer Info": "Info développeur",
    "User Guide": "Mode d'emploi",
    "Support e-mail": "Support e-mail",
    "Our Website": "Notre site Web",
    "App Review": "App Review",
    "Enjoying App? Leave us a review in the App Market.": "Apprécier App? Laissez-nous un commentaire sur l'App Market.",
    "Review Us": "Revoir nous",
    "Connect With Us": "Connecte-toi avec nous",
    "What's your email?": "Quel est ton e-mail?",
    "Invalid email address!": "Adresse e-mail invalide!",
    "Comments": "Commentaires",
    "We'd love to hear from you. Send us a message.": "Nous aimerions beaucoup avoir de vos nouvelles. Envoyez-nous un message.",
    "Message must be at least 5 characters long": "Le message doit comporter au moins 5 caractères",
    "Send": "Envoyer",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Si vous souhaitez autoriser l'utilisateur à basculer entre les vues de l'agenda, activez cette option et choisissez les vues à afficher.",
    "Main": "Principal",
    "Localize": "Localiser",
    "Settings": "Réglages",
    "Layouts": "Agencement",
    "Advanced": "Avancé",
    "Design": "Conception",
    "Support": "Soutien",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Tous les paramètres locaux sont (automatiquement) basés sur votre langue. Si votre langue figure sur la liste, il n'est pas nécessaire de personnaliser cette section.",
    "Date Format":"Format de date",
    "Time Format":"Format de l'heure",
    "Text Direction":"Direction du texte",
    "Left to Right":"De gauche à droite",
    "Right to Left":"De droite à gauche",
    "Week Starts On":"La semaine commence",
    "Agenda Style":"Style de l'ordre du jour",
    "Classic":"Classique",
    "Modern":"Moderne",
    "Agenda Header":"En-tête d'agenda",
    "Upcoming Events":"Évènements à venir",
    "Agenda Event Limit":"Agenda Limite des événements",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"Mettez à niveau maintenant et obtenez beaucoup plus de fonctionnalités et profitez pleinement de votre application!",
    "Upgrade Now":"Mettre à jour maintenant",
    "Hosting events that last all day? This lets you show them on your calendar.": "Organiser des événements qui durent toute la journée? Cela vous permet de les afficher sur votre calendrier.",
    "24 hours":"24 heures",
    "Sat": "Sam",
    "Sun": "Dim",
    "Mon": "Lun",
    "Default": "Défaut",
    "Select custom design style for your calendar.": "Sélectionnez un style de conception personnalisé pour votre calendrier.",
    "Style": "Style",
    "Styles and Colors": "Styles et Couleurs",
    "Calendar Name":"Nom du calendrier",
    "Write your Calendar name here":"Écrivez votre nom de calendrier ici",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"Ce n'est pas visible pour vos utilisateurs. Définissez des noms pour différencier vos calendriers lorsque vous utilisez la fonction Synchronisation du calendrier Boom.",
    "General Info" : "Informations générales",
    "Venue" : "Lieu",
    "Organizer"  : "l' organisateur"

}

export default fr;
