let he = {
    "Language": "שפה",
    "Show Time Zone": "הצג אזור זמן",
    "Custom Local Settings": "הגדרות מקומיות בהתאמה אישית",
    "Add and showcase events on your site using a beautiful calendar.": "הוסף והציג אירועים באתר שלך באמצעות לוח שנה יפה . ",
    "Week Days": "ימי חול",
    "Manage Events": "נהל אירועים",
    "General": "כללי",
    "Layout Picker": "בורר פריסה",
    "Month": "חודש",
    "Monthly": "חודשי",
    "Week": "שבוע",
    "Weekly": "שבועי",
    "Day": "יום",
    "Daily": "יומי",
    "Agenda": "סדר יום",
    "Navigation Buttons": "כפתורי ניווט",
    "Today": "היום",
    "Week numbers": "מספרי שבוע",
    "Include Weekends": "כלול סופי שבוע",
    "All-day": "כל היום",
    "All Day": "כל היום",
    "Label": "תווית",
    "Fit to Height": "מתאים לגובה",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "כדי להגדיר פרופורציות של אפליקציות בטל באופן ידני אפשרות זו ולשנות את גודל לוח השנה בעורך. ",
    "Default Layout": "מערך ברירת מחדל",
    "Monthly view": "תצוגה חודשית",
    "Weekly and Daily view": "תצוגה שבועית ויומית",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "אתה יכול להעניק למבקרים חוויה עקבית יותר על ידי הצגת מספר זהה של שבועות ( 6) בכל פעם.",
    "Fixed Weekly Layout": "מתווה שבועי קבוע",
    "back": " בחזרה ",
    "Row": "שורה",
    "Hours in Weekly View": "שעות בתצוגה שבועית",
    "Hours in Daily View": "שעות בתצוגה יומית",
    "Start": "התחל",
    "End": "סוף",
    "At This Hour": "בשעה זו",
    "Add to": "להוסיף ל",
    "Button": "כפתור",
    "Buttons": "כפתורים",
    "Sunday": "יום ראשון",
    "Monday": "יום שני",
    "Tuesday": "יום שלישי",
    "Wednesday": "יום רביעי",
    "Thursday": "יום חמישי",
    "Friday": "יום שישי",
    "Saturday": "יום שבת",
    "Default Date": "תאריך ברירת מחדל",
    "year": " שנה ",
    "month": " חודש ",
    "days": " ימים ",
    "ago": " לפני ",
    "ahead": " קדימה ",
    "Yesterday": "אתמול",
    "Today": "היום",
    "Tomorrow": "מחר",
    "Custom": "המותאם אישית",
    "Set Daily Rows Limit": "הגדר מגבלת שורות יומיות",
    "Set Proportions": "קבע פרופורציות",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "אפשר המבקר להוסיף האירוע המקומי Calnedars , Google, Yahoo, Outlook, iCalendar . ",
    "Container": "מיכל",
    "Background": "רקע כללי",
    "Container Background": "רקע מיכל",
    "Container Borders": "גבולות מיכל",
    "Calendar": "לוח שנה",
    "Event Info Tooltip": "הסבר הכלים למידע על אירועים",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "כשאנשים מרחפים מעל אירוע הם יראו את כל המידע על זה בסמל הכלים. ",
    "Event Info Window": "חלון פרטי אירוע",
    "This is the full information window that opens when someone clicks on the event.": "זהו חלון המידע המלא שנפתח כשמישהו לוחץ על האירוע. ",
    "Use Gradient": "השתמש בשיפוע",
    "Vertical": "אנכי",
    "Horizontal": "אופקי",
    "First": "ראשון",
    "Second": "שני",
    "diagonal": " אלכסון ",
    "Radial": "רדיאלי",
    "Select option": "בחר אפשרות",
    "Solid": "מוצק",
    "Dotted": "מנוקד",
    "Dashed": "מקווקו",
    "Double": "כפול",
    "Border Radius": "רדיוס הגבול",
    "Padding": "ריפוד",
    "Date Header": "כותרת תאריך",
    "Event Default Color": "צבע ברירת מחדל לאירוע",
    "Days of Week": "ימי השבוע",
    "Days of Week Background": "רקע ימי השבוע",
    "Date": "תאריך",
    "Event Title": "כותרת האירוע",
    "Highlight today": "הדגש היום",
    "Highlight Color": "הדגש צבע",
    "Hide": "להתחבא",
    "Calendar Border Color": "צבע גבול לוח שנה",
    "Calendar Border Width": "רוחב גבול לוח השנה",
    "Calendar Border Style": "סגנון גבול לוח שנה",
    "Font Color": "צבע גופן",
    "Event Background": "רקע אירוע",
    "Card Date Color": "צבע תאריך כרטיס",
    "Title Font": "גופן כותרת",
    "Date Font": "גופן תאריך",
    "Description Font": "גופן תיאור",
    "Button Background": "רקע כפתור",
    "Button Text": "טקסט כפתור",
    "Border Color": "צבע גבול",
    "Border Width": "רוחב גבול",
    "Border Type": "סוג גבול",
    "Title": "כותרת",
    "Description": "תיאור",
    "Background Color": "צבע רקע",
    "Divider": "מחיצה",
    "Event Details Font": "גופן פרטי האירוע",
    "Website Link Color": "צבע קישור לאתר",
    "Developer Info": "מידע על מפתחים",
    "User Guide": "מדריך למשתמש",
    "Support e-mail": "תמיכה בדואר אלקטרוני",
    "Our Website": "האתר שלנו",
    "App Review": "סקירת אפליקציות",
    "Enjoying App? Leave us a review in the App Market.": "נהנה מאפליקציה? השאר לנו ביקורת בשוק האפליקציות. ",
    "Review Us": "סקור אותנו",
    "Connect With Us": "התחבר אלינו",
    "What's your email?": "מה המייל שלך?",
    "Invalid email address!": 'כתובת דוא"ל לא חוקית!',
    "Comments": "הערות",
    "We'd love to hear from you. Send us a message.": "נשמח לשמוע ממך. שלח לנו הודעה. ",
    "Message must be at least 5 characters long": "ההודעה חייבת להיות לפחות 5 תווים",
    "Send": "שלח",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "אם ברצונך לאפשר למשתמש לעבור בין תצוגות לוח השנה, הפעל אפשרות זו ובחר את התצוגות שברצונך להציג. ",
    "Main": "עיקרי",
    "Localize": "לוקליזציה",
    "Settings": "הגדרות",
    "Layouts": "פריסות",
    "Advanced": "מתקדם",
    "Design": "עיצוב",
    "Support": "תמיכה",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "כל ההגדרות המקומיות מבוססות (אוטומטית) על פי שפתך. אם השפה שלך ברשימה, אין צורך להתאים אישית את החלק הזה.",
    "Date Format":"פורמט תאריך",
    "Time Format":"פורמט זמן",
    "Text Direction":"כיוון טקסט",
    "Left to Right":"משמאל לימין",
    "Right to Left":"מימין לשמאל",
    "Week Starts On":"השבוע מתחיל",
    "Agenda Style":"סגנון אג'נדה",
    "Classic":"קלאסי",
    "Modern":"מודרני",
    "Agenda Header":"כותרת סדר יום",
    "Upcoming Events":"אירועים קרובים",
    "Agenda Event Limit":"מגבלת אירוע אג'נדה",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"שדרג עכשיו וקבל הרבה יותר תכונות ותיהנה מהאפליקציה שלך במלואה!",
    "Upgrade Now":"שדרג עכשיו",
    "Hosting events that last all day? This lets you show them on your calendar.":"אירוח אירועים שנמשך כל היום? זה מאפשר לך להראות אותם בלוח השנה שלך.",
    "24 hours":"24 שעות",
    "Sat": "יום שבת",
    "Sun": "יום ראשון",
    "Mon": "יום שני",
    "Default": "ברירת מחדל",
    "Select custom design style for your calendar.": "בחר סגנון עיצוב מותאם אישית ללוח השנה שלך.",
    "Style": "סגנון",
    "Styles and Colors": "סגנונות וצבעים",
    "Calendar Name":"שם לוח השנה",
    "Write your Calendar name here":"כתוב כאן את שם לוח השנה",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"זה לא גלוי למשתמשים שלך. הגדר שמות כדי להבדיל את לוחות השנה שלך בעת השימוש בפונקציית סנכרון לוח השנה של Boom.",
    "General Info" : "מידע כללי",
    "Venue" : "מקום",
    "Organizer"  : "מארגן"
};

export default he;
