let hi = {
    "Language": "भाषा",
    "Show Time Zone": "समय क्षेत्र दिखाएं",
    "Custom Local Settings": "कस्टम स्थानीय सेटिंग",
    "Add and showcase events on your site using a beautiful calendar.": "एक सुंदर कैलेंडर का उपयोग करके अपनी साइट पर इवेंट जोड़ें और दिखाएं । ",
    "Week Days": "सप्ताह के दिन",
    "Manage Events": "ईवेंट प्रबंधित करें",
    "General": "सामान्य",
    "Layout Picker": "लेआउट पिकर",
    "Month": "महीना",
    "Monthly": "महीने के",
    "Week": "सप्ताह",
    "Weekly": "साप्ताहिक",
    "Day": "दिवस",
    "Daily": "रोज",
    "Agenda": "एजेंडा",
    "Navigation Buttons": "नेविगेशन बटन",
    "Today": "आज",
    "Week numbers": "सप्ताह संख्या",
    "Include Weekends": "सप्ताहांत शामिल करें",
    "All-day": "पूरे दिन",
    "All Day": "पूरे दिन",
    "Label": "लेबल",
    "Fit to Height": "फिट टू हाइट",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "ऐप अनुपात सेट करने के लिए इस विकल्प को मैन्युअल रूप से अक्षम करें और संपादक में कैलेंडर का आकार बदलें। ",
    "Default Layout": "मूलभूत ढांचा",
    "Monthly view": "मासिक दृश्य",
    "Weekly and Daily view": "साप्ताहिक और दैनिक दृश्य",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "आप एक बार में एक ही सप्ताह ( 6) दिखा कर आगंतुकों को अधिक सुसंगत अनुभव दे सकते हैं ।",
    "Fixed Weekly Layout": "फिक्स्ड साप्ताहिक लेआउट",
    "back": " वापस ",
    "Row": "पंक्ति",
    "Hours in Weekly View": "साप्ताहिक दृश्य में घंटे",
    "Hours in Daily View": "दैनिक दृश्य में घंटे",
    "Start": "शुरु",
    "End": "समाप्त",
    "At This Hour": "इस घंटे",
    "Add to": "में जोड़े",
    "Button": "बटन",
    "Buttons": "बटन",
    "Sunday": "रविवार",
    "Monday": "सोमवार",
    "Tuesday": "मंगलवार",
    "Wednesday": "बुधवार",
    "Thursday": " गुरुवार ",
    "Friday": "शुक्रवार",
    "Saturday": "शनिवार",
    "Default Date": "डिफ़ॉल्ट तिथि",
    "year": " वर्ष ",
    "month": " महीना ",
    "days": " दिन ",
    "ago": " पहले ",
    "ahead": " आगे ",
    "Yesterday": "बिता कल",
    "Today": "आज",
    "Tomorrow": "आने वाला कल",
    "Custom": "कस्टम",
    "Set Daily Rows Limit": "दैनिक पंक्तियाँ सीमा निर्धारित करें",
    "Set Proportions": "सेट अनुपात",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "आगंतुक को स्थानीय कैलेंडर में घटना जोड़ने की अनुमति दें , Google, Yahoo, Outlook, ICalendar । ",
    "Container": "कंटेनर",
    "Background": "पृष्ठभूमि",
    "Container Background": "कंटेनर पृष्ठभूमि",
    "Container Borders": "कंटेनर बॉर्डर",
    "Calendar": "कैलेंडर",
    "Event Info Tooltip": "घटना की जानकारी टूलटिप",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "जब लोग किसी घटना पर होवर करते हैं तो वे इसके बारे में सारी जानकारी टूलटिप में देखेंगे। ",
    "Event Info Window": "इवेंट इंफो विंडो",
    "This is the full information window that opens when someone clicks on the event.": "यह पूरी जानकारी विंडो है जो किसी के घटना पर क्लिक करने पर खुलती है। ",
    "Use Gradient": "ग्रेडिएंट का उपयोग करें",
    "Vertical": "लंबवत",
    "Horizontal": "क्षैतिज",
    "First": "प्रथम",
    "Second": "दूसरा",
    "diagonal": " विकर्ण ",
    "Radial": "रेडियल",
    "Select option": "विकल्प चुनें",
    "Solid": "ठोस",
    "Dotted": "बिंदीदार",
    "Dashed": "डैश्ड",
    "Double": "डबल",
    "Border Radius": "सीमा त्रिज्या",
    "Padding": "गद्दी",
    "Date Header": "तिथि हैडर",
    "Event Default Color": "ईवेंट डिफ़ॉल्ट रंग",
    "Days of Week": "सप्ताह के दिन",
    "Days of Week Background": "सप्ताह की पृष्ठभूमि के दिन",
    "Date": "दिनांक",
    "Event Title": "कार्यक्रम का शीर्षक",
    "Highlight today": "आज हाइलाइट करें",
    "Highlight Color": "हाइलाइट रंग",
    "Hide": "छिपाना",
    "Calendar Border Color": "कैलेंडर बॉर्डर कलर",
    "Calendar Border Width": "कैलेंडर बॉर्डर चौड़ाई",
    "Calendar Border Style": "कैलेंडर बॉर्डर स्टाइल",
    "Font Color": "लिपि का रंग",
    "Event Background": "इवेंट बैकग्राउंड",
    "Card Date Color": "कार्ड की तारीख का रंग",
    "Title Font": "टाइटल फ़ॉन्ट",
    "Date Font": "दिनांक फ़ॉन्ट",
    "Description Font": "विवरण विवरण",
    "Button Background": "बटन पृष्ठभूमि",
    "Button Text": "टेक्स्ट बटन",
    "Border Color": "किनारे का रंग",
    "Border Width": "सीमा चौड़ाई",
    "Border Type": "सीमा प्रकार",
    "Title": "शीर्षक",
    "Description": "विवरण",
    "Background Color": "पीछे का रंग",
    "Divider": "विभाजक",
    "Event Details Font": "ईवेंट विवरण फ़ॉन्ट",
    "Website Link Color": "वेबसाइट लिंक रंग",
    "Developer Info": "डेवलपर",
    "User Guide": "उपयोगकर्ता गाइड",
    "Support e-mail": "ई-मेल का समर्थन करें",
    "Our Website": "हमारी वेबसाइट",
    "App Review": "ऐप रिव्यू",
    "Enjoying App? Leave us a review in the App Market.": "ऐप का आनंद लेना । ऐप मार्केट में हमें एक समीक्षा छोड़ दें । ",
    "Review Us": "हमारी समीक्षा करें",
    "Connect With Us": "हमसे जुडे",
    "What's your email?": "आपका ईमेल क्या है? ",
    "Invalid email address!": "अमान्य ईमेल पता! ",
    "Comments": "टिप्पणियाँ",
    "We'd love to hear from you. Send us a message.": "हम आपसे सुनना पसंद करेंगे। हमें एक संदेश भेजें। ",
    "Message must be at least 5 characters long": "संदेश कम से कम 5 वर्ण लंबा होना चाहिए",
    "Send": "भेजें",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "यदि आप उपयोगकर्ता को कैलेंडर विचारों के बीच स्विच करने की अनुमति देना चाहते हैं, तो इस विकल्प को सक्षम करें और उन विचारों को चुनें जिन्हें आप दिखाना चाहते हैं। ",
    "Main": "मुख्य",
    "Localize": "स्थानीय बनाना",
    "Settings": "सेटिंग्स",
    "Layouts": "लेआउट",
    "Advanced": "उन्नत",
    "Design": "डिज़ाइन",
    "Support": "समर्थन",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "आपकी भाषा के आधार पर सभी स्थानीय सेटिंग्स (स्वचालित रूप से) हैं। यदि आपकी भाषा सूची में है, तो इस अनुभाग को अनुकूलित करने की कोई आवश्यकता नहीं है।",
    "Date Format":"डेटा प्रारूप",
    "Time Format":"समय प्रारूप",
    "Text Direction":"पाठ की दिशा",
    "Left to Right":"बाएं से दाएं",
    "Right to Left":"दाएं से बाएं",
    "Week Starts On":"सप्ताह की शुरुआत",
    "Agenda Style":"एजेंडा स्टाइल",
    "Classic":"क्लासिक",
    "Modern":"आधुनिक",
    "Agenda Header":"एजेंडा हैडर",
    "Upcoming Events":"आने वाले कार्यक्रम",
    "Agenda Event Limit":"एजेंडा इवेंट लिमिट",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"अब अपग्रेड करें और बहुत अधिक सुविधाएं प्राप्त करें और अपने एपीपी का पूरा आनंद लें!",
    "Upgrade Now":"अभी अपग्रेड करें",
    "Hosting events that last all day? This lets you show them on your calendar.":"पूरे दिन चलने वाली घटनाओं की मेजबानी करना; इससे आप उन्हें अपने कैलेंडर पर दिखा सकते हैं।",
    "24 hours":"चौबीस घंटे",
    "Sun": "रविवार",
    "Mon": "सोमवार",
    "Sat": "शनिवार",
    "Default": "चूक",
    "Select custom design style for your calendar.": "अपने कैलेंडर के लिए कस्टम डिज़ाइन शैली का चयन करें।",
    "Style": "अंदाज",
    "Styles and Colors": "शैलियाँ और रंग",
    "Calendar Name":"कैलेंडर का नाम",
    "Write your Calendar name here":"अपने कैलेंडर का नाम यहाँ लिखें",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"यह आपके उपयोगकर्ताओं को दिखाई नहीं देता है। बूम कैलेंडर सिंक फ़ंक्शन का उपयोग करते समय अपने कैलेंडर को अलग करने के लिए नाम सेट करें।",
    "General Info" : "सामान्य जानकारी",
    "Venue" : "स्थान",
    "Organizer"  : "व्यवस्था करनेवाला"
};

export default hi;
