let hu = {
    "Language": "Nyelv",
    "Show Time Zone": "Mutasson Idő zónát",
    "Custom Local Settings": "Egyedi hely beállítás",
    "Add and showcase events on your site using a beautiful calendar.": "Adj hozzá eseményeket az oldaladhoz, ezzel a csodás naptárral.",
    "Week Days": 'Hétköznapok',
    "Manage Events": "Események kezelése",
    "General": "Általános",
    "Layout Picker": "Kinézet választó",
    "Month": "Hónap",
    "Monthly": "Havonta",
    "Week": "Hét",
    "Weekly": "Hetente",
    "Day": "Nap",
    "Daily": "Naponta",
    "Agenda": "Napirend",
    "Navigation Buttons": "Irányító gombok",
    "Today": "Ma",
    "Week numbers": "Hetek számozása",
    "Include Weekends": "Hétvégét belevéve",
    "All Day": "Egész nap",
    "Label": "Felirat",
    "Fit to Height": "Magassághoz igazítva",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "Az alkalmazás méretének manuális beállításához tiltsale ezt a lehetőséget, és méretezzé át a Naptár szerkesztőben.",
    "Default Layout": "Alapértelmezett nézet",
    "Monthly view": "Havi nézet",
    "Weekly and Daily view": "Heti és Napi nézet",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "A látogatóknak nyújts következetesebb érzést azzal, hogy ugyanazt a hetet mutatod.",
    "Fixed Weekly Layout": "Fix heti kinézet",
    "back": "vissza",
    "Row": "Sor",
    "Hours in Weekly View": "Órák a heti nézetben",
    "Hours in Daily View": "Órák a napi nézetben",
    "Start": "Kezdés",
    "End": "Vége",
    "At This Hour": "Ebben az órában",
    "Add to": "Hozzáad",
    "Button": "Gomb",
    "Buttons": "Gombok",
    "Sunday": "Vasárnap",
    "Monday": "Hétfő",
    "Tuesday": "Kedd",
    "Wednesday": "Szerda",
    "Thursday": "Csütörtök",
    "Friday": "Péntek",
    "Saturday": "Szombat",
    "Default Date": "Alapértelmezett dátum",
    "year": "év",
    "month": "hónap",
    "days": "napok",
    "ago": "előtt",
    "ahead": "előre",
    "Yesterday": "Tegnap",
    "Today": "Ma",
    "Tomorrow": "Holnap",
    "Custom": "Egyedi",
    "Set Daily Rows Limit": "Állíts napi sor limitet",
    "Set Proportions": "Állíts tagolást",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Engedélyezd a látogatóknak, hogy hozzáadják az eseményeket a saját naptárjukhoz = Google, Yahoo, Outlook, ICalender.",
    "Container": "Tartó",
    "Background": "Háttér",
    "Container Background": "Tartó háttér",
    "Container Borders": "Tartó keretek",
    "Calendar": "Naptár",
    "Event Info Tooltip": "Esemény info tanács",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "Amikor az emberek az egérmutatót egy esemény fölé viszik, akkor azerről szóló összes információt egy leírásban látják.",
    "Event Info Window": "Esemény Info Ablak",
    "This is the full information window that opens when someone clicks on the event.": "Ez a full információ ablak, ha valaki rákattint az eseményre,Use Gradient = Használja a színátmenetet",
    "Use Gradient": "Használja a színátmenetet",
    "Vertical": "Vertikális",
    "Horizontal": "Horizontális",
    "First": "Első",
    "Second": "Második",
    "diagonal": "átló",
    "Radial": "Sugár",
    "Select option": "Választható opció",
    "Solid": "Szolid",
    "Dotted": "Pontos",
    "Dashed": "Szaggatott",
    "Double": "Kettős",
    "Border Radius": "Határ sugár",
    "Padding": "Tömés",
    "Date Header": "Dátum fejléc",
    "Event Default Color": "Esemény alapértelmezett szín",
    "Days of Week": "A hét napjai",
    "Days of Week Background": "A hét napjai háttere",
    "Date": "Dátum",
    "Event Title": "Esemény címe",
    "Highlight today": "Kiemelés ma",
    "Highlight Color": "Kiemelés szín",
    "Hide": "Elrejt",
    "Calendar Border Color": "Naptár keret szín",
    "Calendar Border Width": "Naptár keret szélesség",
    "Calendar Border Style": "Naptár keret stílus",
    "Font Color": "Betűtípus szín",
    "Event Background": "Esemény háttér",
    "Card Date Color": "Kártya datum szín",
    "Title Font": "Cím betűtípus",
    "Date Font": "Dátum betűtípus",
    "Description Font": "Leírás betűtípus",
    "Button Background": "Gomb háttér",
    "Button Text": "Gomb szöveg",
    "Border Color": "Keret szín",
    "Border Width": "Keret szélesség",
    "Border Type": "Keret típus",
    "Title": "Cím",
    "Description": "Leírás",
    "Background Color": "Háttér szín",
    "Divider": "Osztó",
    "Event Details Font": "Esemény leírás betűtípus",
    "Website Link Color": "Weboldal link szín",
    "Developer Info": "Fejlesztői Info",
    "User Guide": "Használati útmutató",
    "Support e-mail": "Ügyfélszolgálat e-mail",
    "Our Website": "Mi weboldalunk",
    "App Review": "App értékelés",
    "Enjoying App? Leave us a review in the App Market.": "Tetszik az app? Írj egy értékelés az App Marketben.",
    "Review Us": "Értékelj minket",
    "Connect With Us": "Lépj kapcsolatban velünk",
    "What's your email?": "Mi az email címed?",
    "Invalid email address!": "Helytelen email cím!",
    "Comments": "Kommentek",
    "We'd love to hear from you. Send us a message.": "Örömmel hallunk felőled! Írj üzenetet nekünk.",
    "Message must be at least 5 characters long": "Az üzenetnek minimum 5 karakter hosszúságúnak kell hogy legyen",
    "Send": "Küldés",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Ha azt szeretnéd hogy a felhasználók tudjanak váltani a naptár nézet között, engedélyezd ezt a opciót és válassza ki a megjeleníteni kívánt nézetet.",
    "Main": "Főoldal",
    "Localize": "Hely",
    "Settings": "Beállítások",
    "Layouts": "Kinézetek",
    "Advanced": "Haladó",
    "Design": "Kinézet",
    "Support": "Segítség",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Az összes helyi beállítás (automatikusan) az Ön nyelvén alapul. Ha az Ön nyelve szerepel a listán, akkor nem kell testreszabnia ezt a részt.",
    "Date Format":"Dátum formátum",
    "Time Format":"Idő formátum",
    "Text Direction":"Szöveg irány",
    "Left to Right":"Balról jobbra",
    "Right to Left":"Jobbról balra",
    "Week Starts On":"Hét kezdés",
    "Agenda Style":"Napirend stílus",
    "Classic":"Klasszik",
    "Modern":"Modern",
    "Agenda Header": "Napirend fejléc",
    "Upcoming Events":"Közeledő események",
    "Agenda Event Limit":"Napirend esemény limit",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"Bővíts most és aktiválj több lehetőséget, hogy teljes mértékben élvezd az APP- ot!",
    "Upgrade Now":"Bővíts most",
    "Hosting events that last all day? This lets you show them on your calendar.":"Egésznapos események? Ez lehetővé teszi, hogy megmutassa őket a naptárban.",
    "24 hours":"24 órás",
    "Sun": "Vas",
    "Mon": "Hét",
    "Sat": "Szom",
    "Default": "Alapértelmezett",
    "Style":"Stílus",
    "Calendar Name":"Naptár neve",
    "Write your Calendar name here":"Írja ide a naptár nevét",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"Ez a felhasználók számára nem látható. Nevek beállítása a naptárak megkülönböztetésére a Boom Calendar Sync funkció használatakor.",
    "General Info" : "Általános információ",
    "Venue" : "Helyszín",
    "Organizer"  : "Szervező"
}

export default hu;
