let it = {
    "Language": "Linguaggio",
    "Show Time Zone": "Mostra fuso orario",
    "Custom Local Settings": "Impostazioni locali personalizzate",
    "Add and showcase events on your site using a beautiful calendar.": "Aggiungi e mostra gli eventi sul tuo sito utilizzando un bellissimo calendario . ",
    "Week Days": "Giorni della settimana",
    "Manage Events": "Gestisci eventi",
    "General": "Generale",
    "Layout Picker": "Selettore layout",
    "Month": "Mese",
    "Monthly": "Mensile",
    "Week": "Settimana",
    "Weekly": "Settimanalmente",
    "Day": "Giorno",
    "Daily": "Quotidiano",
    "Agenda": "Agenda",
    "Navigation Buttons": "Pulsanti di navigazione",
    "Today": "Oggi",
    "Week numbers": "Numeri settimanali",
    "Include Weekends": "Includi fine settimana",
    "All-day": "Tutto il giorno",
    "All Day": "Tutto il giorno",
    "Label": "Etichetta",
    "Fit to Height": "Adatta all'altezza",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "Per impostare proporzioni app disabilita manualmente questa opzione e ridimensiona il calendario in Editor. ",
    "Default Layout": "Layout predefinito",
    "Monthly view": "Vista mensile",
    "Weekly and Daily view": "Vista settimanale e giornaliera",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Puoi offrire ai visitatori un'esperienza più coerente mostrando lo stesso numero di settimane ( 6) alla volta.",
    "Fixed Weekly Layout": "Layout settimanale fisso",
    "back": " indietro ",
    "Row": "Riga",
    "Hours in Weekly View": "Ore nella vista settimanale",
    "Hours in Daily View": "Ore nella vista giornaliera",
    "Start": "Inizio",
    "End": "Fine",
    "At This Hour": "A quest'ora",
    "Add to": "Aggiungere a",
    "Button": "Pulsante",
    "Buttons": "Pulsanti",
    "Sunday": "Domenica",
    "Monday": "Lunedi",
    "Tuesday": "Martedì",
    "Wednesday": "Mercoledì",
    "Thursday": " Giovedì ",
    "Friday": "Venerdì",
    "Saturday": "Sabato",
    "Default Date": "Data predefinita",
    "year": " anno ",
    "month": " mese ",
    "days": " giorni ",
    "ago": " ago ",
    "ahead": " avanti ",
    "Yesterday": "Ieri",
    "Today": "Oggi",
    "Tomorrow": "Domani",
    "Custom": "Custom",
    "Set Daily Rows Limit": "Imposta limite righe giornaliere",
    "Set Proportions": "Imposta proporzioni",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Consenti al visitatore di aggiungere un evento ai Calnedars locali , Google, Yahoo, Outlook, ICalendar . ",
    "Container": "Contenitore",
    "Background": "Sfondo",
    "Container Background": "Sfondo contenitore",
    "Container Borders": "Confini del contenitore",
    "Calendar": "Calendario",
    "Event Info Tooltip": "Descrizione info evento",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "Quando le persone passano il mouse sopra un evento vedranno tutte le informazioni a riguardo in una descrizione comandi. ",
    "Event Info Window": "Finestra informazioni evento",
    "This is the full information window that opens when someone clicks on the event.": "Questa è la finestra con le informazioni complete che si apre quando qualcuno fa clic sull'evento. ",
    "Use Gradient": "Usa sfumatura",
    "Vertical": "Verticale",
    "Horizontal": "Orizzontale",
    "First": "Primo",
    "Second": "Secondo",
    "diagonal": " diagonale ",
    "Radial": "Radiale",
    "Select option": "Selezionare l'opzione",
    "Solid": "Solido",
    "Dotted": "Tratteggiata",
    "Dashed": "Tratteggiata",
    "Double": "Doppio",
    "Border Radius": "Raggio di confine",
    "Padding": "Imbottitura",
    "Date Header": "Intestazione data",
    "Event Default Color": "Colore predefinito evento",
    "Days of Week": "Giorni della settimana",
    "Days of Week Background": "Sfondo giorni della settimana",
    "Date": "Data",
    "Event Title": "Titolo dell'evento",
    "Highlight today": "Evidenzia oggi",
    "Highlight Color": "Evidenzia colore",
    "Hide": "Nascondere",
    "Calendar Border Color": "Colore bordo calendario",
    "Calendar Border Width": "Larghezza bordo calendario",
    "Calendar Border Style": "Stile bordo calendario",
    "Font Color": "Colore del carattere",
    "Event Background": "Sfondo dell'evento",
    "Card Date Color": "Colore data carta",
    "Title Font": "Carattere del titolo",
    "Date Font": "Carattere data",
    "Description Font": "Carattere descrizione",
    "Button Background": "Sfondo pulsante",
    "Button Text": "Testo pulsante",
    "Border Color": "Colore del bordo",
    "Border Width": "Larghezza del bordo",
    "Border Type": "Tipo di bordo",
    "Title": "Titolo",
    "Description": "Descrizione",
    "Background Color": "Colore di sfondo",
    "Divider": "Divisore",
    "Event Details Font": "Carattere dettagli evento",
    "Website Link Color": "Colore link sito Web",
    "Developer Info": "Informazioni sviluppatore",
    "User Guide": "Guida utente",
    "Support e-mail": "Supporto e-mail",
    "Our Website": "Il nostro sito web",
    "App Review": "Revisione app",
    "Enjoying App? Leave us a review in the App Market.": "Ti piace l'app? Lasciaci una recensione nel mercato delle app. ",
    "Review Us": "Revisionaci",
    "Connect With Us": "Mettiti in comunicazione con noi",
    "What's your email?": "Qual è la tua email? ",
    "Invalid email address!": "Indirizzo email non valido! ",
    "Comments": "Commenti",
    "We'd love to hear from you. Send us a message.": "Ci piacerebbe avere tue notizie. Inviaci un messaggio. ",
    "Message must be at least 5 characters long": "Il messaggio deve contenere almeno 5 caratteri",
    "Send": "Inviare",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Se si desidera consentire all'utente di alternare le visualizzazioni del calendario, abilitare questa opzione e scegliere le visualizzazioni che si desidera mostrare. ",
    "Main": "Principale",
    "Localize": "Localizzare",
    "Settings": "Impostazioni",
    "Layouts": "Disposizione",
    "Advanced": "Avanzati",
    "Design": "Disegno",
    "Support": "Supporto",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Tutte le impostazioni locali sono (automaticamente) in base alla tua lingua. Se la tua lingua è nell'elenco, non è necessario personalizzare questa sezione.",
    "Date Format":"Formato data",
    "Time Format":"Formato orario",
    "Text Direction":"Direzione del testo",
    "Left to Right":"Da sinistra a destra",
    "Right to Left":"Da destra a sinistra",
    "Week Starts On":"La settimana inizia",
    "Agenda Style":"Stile agenda",
    "Classic":"Classico",
    "Modern":"Moderno",
    "Agenda Header":"Intestazione agenda",
    "Upcoming Events":"Prossimi eventi",
    "Agenda Event Limit":"Limite eventi agenda",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"Esegui l'upgrade ora e ottieni molte più funzioni e goditi appieno la tua APP!",
    "Upgrade Now":"Aggiorna ora",
    "Hosting events that last all day? This lets you show them on your calendar.":"Ospitare eventi che durano tutto il giorno? Questo ti consente di mostrarli sul tuo calendario.",
    "24 hours":"24 ore",
    "Sat": "Sab",
    "Sun": "Dom",
    "Mon": "Lun",
    "Default": "Predefinito",
    "Select custom design style for your calendar.": "Seleziona uno stile di design personalizzato per il tuo calendario.",
    "Style": "Stile",
    "Styles and Colors": "Stili e colori",
    "Calendar Name":"Nome del calendario",
    "Write your Calendar name here":"Scrivi qui il nome del tuo calendario",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"Questo non è visibile ai tuoi utenti. Imposta i nomi per differenziare i tuoi calendari quando usi la funzione Sincronizzazione Boom Calendar.",
    "General Info" : "Informazioni generali",
    "Venue" : "Sede",
    "Organizer"  : "il promotore"
}

export default it;
