let ja = {
    "Language": "言語",
    "Show Time Zone": "タイムゾーンを表示",
    "Custom Local Settings": "カスタムローカル設定",
    "Add and showcase events on your site using a beautiful calendar.": "美しいカレンダーを使ってあなたのサイトにイベントを追加して展示する。",
    "Week Days": "平日",
    "Manage Events": "イベント管理",
    "General": "一般",
    "Layout Picker": "レイアウトピッカー",
    "Month": "月",
    "Monthly": "毎月",
    "Week": "週間",
    "Weekly": "毎週",
    "Day": "日",
    "Daily": "毎日",
    "Agenda": "アジェンダ",
    "Navigation Buttons": "ナビゲーションボタン",
    "Today": "今日",
    "Week numbers": "週番号",
    "Include Weekends": "週末を含める",
    "All-day": "一日中",
    "All Day": "一日中",
    "Label": "ラベル",
    "Fit to Height": "「高さに合わせる」",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "「アプリのプロポーションを設定するには、このオプションを手動で無効にして、エディタのカレンダーのサイズを変更します。」",
    "Default Layout": "デフォルトレイアウト",
    "Monthly view": "月別ビュー",
    "Weekly and Daily view": "週次と日次の表示",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "「一度に同じ週数（6）を表示することで、訪問者により一貫したエクスペリエンスを提供できます。」",
    "Fixed Weekly Layout": "毎週の固定レイアウト",
    "back": " 戻る",
    "Row": "行",
    "Hours in Weekly View": "週間ビューの時間",
    "Hours in Daily View": "デイリービューの時間",
    "Start": "開始",
    "End": "終わり",
    "At This Hour": "「この時」",
    "Add to": "追加",
    "Button": "ボタン",
    "Buttons": "ボタン",
    "Sunday": "日曜日",
    "Monday": "月曜",
    "Tuesday": "火曜日",
    "Wednesday": "水曜日",
    "Thursday": " 木曜日",
    "Friday": "金曜日",
    "Saturday": "土曜日",
    "Default Date": "デフォルトの日付",
    "year": " 年",
    "month": " 月",
    "days": " 日数",
    "ago": " 前",
    "ahead": " 先",
    "Yesterday": "昨日",
    "Today": "今日",
    "Tomorrow": "明日",
    "Custom": "カスタム",
    "Set Daily Rows Limit": "1日の行数の上限を設定",
    "Set Proportions": "「比率の設定」",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "訪問者が地元のCalnedarsにイベントを追加することを許可する,Google、Yahoo、Outlook、ICalendar 。",
    "Container": "容器",
    "Background": "バックグラウンド",
    "Container Background": "コンテナの背景",
    "Container Borders": "コンテナの枠線",
    "Calendar": "カレンダー",
    "Event Info Tooltip": "イベント情報ツールチップ",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "「イベントにカーソルを合わせると、ツールチップにそのイベントに関するすべての情報が表示されます。」",
    "Event Info Window": "イベント情報ウィンドウ",
    "This is the full information window that opens when someone clicks on the event.": "「これは、誰かがイベントをクリックしたときに開く完全な情報ウィンドウです。」",
    "Use Gradient": "「グラデーションを使う」",
    "Vertical": "垂直",
    "Horizontal": "水平",
    "First": "最初",
    "Second": "「セカンド」",
    "diagonal": " 対角線",
    "Radial": "ラジアル",
    "Select option": "オプションを選択",
    "Solid": "固体",
    "Dotted": "点在",
    "Dashed": "ダッシュ",
    "Double": "ダブル",
    "Border Radius": "ボーダー半径",
    "Padding": "パディング",
    "Date Header": "日付ヘッダ",
    "Event Default Color": "イベントデフォルトカラー",
    "Days of Week": "曜日",
    "Days of Week Background": "曜日の経歴",
    "Date": "日付",
    "Event Title": "イベントのタイトル",
    "Highlight today": "今日のハイライト",
    "Highlight Color": "ハイライトカラー",
    "Hide": "隠す",
    "Calendar Border Color": "カレンダー枠の色",
    "Calendar Border Width": "カレンダー枠の幅",
    "Calendar Border Style": "「カレンダー枠スタイル」",
    "Font Color": "フォントの色",
    "Event Background": "「イベントの背景」",
    "Card Date Color": "「カード日付の色」",
    "Title Font": "タイトルフォント",
    "Date Font": "日付フォント",
    "Description Font": "説明フォント",
    "Button Background": "「ボタンの背景」 ",
    "Button Text": "ボタンテキスト",
    "Border Color": "ボーダの色",
    "Border Width": "枠の幅",
    "Border Type": "枠の種類",
    "Title": "タイトル",
    "Description": "説明",
    "Background Color": "「背景色」",
    "Divider": "仕切り",
    "Event Details Font": "イベント詳細フォント",
    "Website Link Color": "Webサイトのリンクの色",
    "Developer Info": "開発者情報",
    "User Guide": "ユーザーガイド",
    "Support e-mail": "サポートメール",
    "Our Website": "私たちのウェブサイト",
    "App Review": "アプリレビュー",
    "Enjoying App? Leave us a review in the App Market.": "Appを楽しんでいますか？App Marketでレビューを残してください。",
    "Review Us": "私達を見直しなさい",
    "Connect With Us": "「私達とつながりなさい」",
    "What's your email?": "あなたのEメールは何ですか？",
    "Invalid email address!": "無効なメールアドレスです！",
    "Comments": "コメント",
    "We'd love to hear from you. Send us a message.": "「私たちはあなたから話を聞きたいです。私たちにメッセージを送ってください。」",
    "Message must be at least 5 characters long": "メッセージは5文字以上でなければなりません",
    "Send": "送信",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "「ユーザーにカレンダー表示の切り替えを許可する場合は、このオプションを有効にして表示したい表示を選択してください。」",
    "Main": "メイン",
    "Localize": "ローカライズ",
    "Settings": "設定",
    "Layouts": "レイアウト",
    "Advanced": "高度な",
    "Design": "設計",
    "Support": "サポート",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "すべてのローカル設定は（自動的に）あなたの言語に基づいています。 あなたの言語がリストに載っていれば、このセクションをカスタマイズする必要はありません。",
    "Date Format":"日付形式",
    "Time Format":"時間形式",
    "Text Direction":"テキストの方向",
    "Left to Right":"左から右へ",
    "Right to Left":"右から左へ",
    "Week Starts On":"週の始まり",
    "Agenda Style":"アジェンダスタイル",
    "Classic":"クラシック",
    "Modern":"モダン",
    "Agenda Header":"アジェンダヘッダー",
    "Upcoming Events":"今後のイベント",
    "Agenda Event Limit":"アジェンダイベント制限",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"今すぐアップグレードして、さらに多くの機能を入手し、APPを完全に楽しみましょう！",
    "Upgrade Now":"今すぐアップグレード",
    "Hosting events that last all day? This lets you show them on your calendar.":"終日開催するイベントをホストしていますか？これにより、カレンダーにイベントを表示できます。",
    "24 hours":"24時間",
    "Sun": "日曜日",
    "Mon": "月曜",
    "Sat": "土曜日",
    "Default": "デフォルト",
    "Select custom design style for your calendar.": "カレンダーのカスタムデザインスタイルを選択します",
    "Style": "スタイル",
    "Styles and Colors": "スタイルと色",
    "Calendar Name":"カレンダー名",
    "Write your Calendar name here":"ここにカレンダー名を書いてください",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"これはユーザーには見えません。 ブームカレンダー同期機能を使用する場合は、名前を設定してカレンダーを区別します。",
    "General Info" : "一般的な情報",
    "Venue" : "会場",
    "Organizer"  : "主催者"
}

export default ja;
