let ko = {
    "Language": "언어",
    "Show Time Zone": "시간대 표시",
    "Custom Local Settings": "맞춤 지역 설정",
    "Add and showcase events on your site using a beautiful calendar.": "아름다운 캘린더를 사용하여 사이트의 이벤트를 추가하고 보여줍니다 . ",
    "Week Days": "주중 일",
    "Manage Events": "이벤트 관리",
    "General": "일반",
    "Layout Picker": "레이아웃 선택 도구",
    "Month": "달",
    "Monthly": "월간 간행물",
    "Week": "주",
    "Weekly": "주간",
    "Day": "일",
    "Daily": "매일",
    "Agenda": "비망록",
    "Navigation Buttons": "탐색 버튼",
    "Today": "오늘",
    "Week numbers": "주 번호",
    "Include Weekends": "주말 포함",
    "All-day": "하루 종일",
    "All Day": "하루 종일",
    "Label": "상표",
    "Fit to Height": "높이에 맞추기",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "앱 비율을 설정하려면이 옵션을 비활성화하고 편집기에서 캘린더의 크기를 조정하십시오.",
    "Default Layout": "기본 레이아웃",
    "Monthly view": "월간보기",
    "Weekly and Daily view": "주간 및 일일보기",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "한 번에 같은 주 수 ( 6)를 표시함으로써 방문자에게보다 일관된 경험을 제공 할 수 있습니다 .",
    "Fixed Weekly Layout": "고정 주간 레이아웃",
    "back": " 뒤로 ",
    "Row": "열",
    "Hours in Weekly View": "주간보기 시간",
    "Hours in Daily View": "일일보기 시간",
    "Start": "스타트",
    "End": "종료",
    "At This Hour": "이 시간에",
    "Add to": "다음에 추가",
    "Button": "단추",
    "Buttons": "버튼",
    "Sunday": "일요일",
    "Monday": "월요일",
    "Tuesday": "화요일",
    "Wednesday": "수요일",
    "Thursday": " 목요일 ",
    "Friday": "금요일",
    "Saturday": "토요일",
    "Default Date": "기본 날짜",
    "year": " 년 ",
    "month": " 월 ",
    "days": " 일 ",
    "ago": " 이전 ",
    "ahead": " 앞으로 ",
    "Yesterday": "어제",
    "Today": "오늘",
    "Tomorrow": "내일",
    "Custom": "관습",
    "Set Daily Rows Limit": "일일 행 제한 설정",
    "Set Proportions": "비율 설정",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "방문자가 지역 Calnedars : Google, Yahoo, Outlook, ICalendar에 이벤트를 추가 할 수 있습니다.",
    "Container": "컨테이너",
    "Background": "배경",
    "Container Background": "컨테이너 배경",
    "Container Borders": "컨테이너 테두리",
    "Calendar": "달력",
    "Event Info Tooltip": "이벤트 정보 툴팁",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "사람들이 이벤트에 마우스를 가져 가면 툴팁에 모든 정보가 표시됩니다. ",
    "Event Info Window": "이벤트 정보 창",
    "This is the full information window that opens when someone clicks on the event.": "이것은 누군가가 이벤트를 클릭하면 열리는 전체 정보 창입니다. ",
    "Use Gradient": "그라디언트 사용",
    "Vertical": "수직선",
    "Horizontal": "수평 적",
    "First": "먼저",
    "Second": "둘째",
    "diagonal": " 대각선 ",
    "Radial": "방사형",
    "Select option": "선택 옵션",
    "Solid": "고체",
    "Dotted": "점이 찍힌",
    "Dashed": "Dashed",
    "Double": "더블",
    "Border Radius": "테두리 반지름",
    "Padding": "심",
    "Date Header": "날짜 헤더",
    "Event Default Color": "이벤트 기본 색상",
    "Days of Week": "요일",
    "Days of Week Background": "요일 배경",
    "Date": "날짜",
    "Event Title": "이벤트 제목",
    "Highlight today": "오늘 하이라이트",
    "Highlight Color": "하이라이트 색상",
    "Hide": "숨는 장소",
    "Calendar Border Color": "일정 테두리 색",
    "Calendar Border Width": "일정 테두리 너비",
    "Calendar Border Style": "일정 테두리 스타일",
    "Font Color": "글꼴 색상",
    "Event Background": "이벤트 배경",
    "Card Date Color": "카드 날짜 색상",
    "Title Font": "제목 글꼴",
    "Date Font": "날짜 글꼴",
    "Description Font": "설명 글꼴",
    "Button Background": "버튼 배경",
    "Button Text": "버튼 텍스트",
    "Border Color": "테두리 색상",
    "Border Width": "테두리 너비",
    "Border Type": "테두리 유형",
    "Title": "표제",
    "Description": "기술",
    "Background Color": "배경색",
    "Divider": "분할기",
    "Event Details Font": "이벤트 세부 정보 글꼴",
    "Website Link Color": "웹 사이트 링크 색상",
    "Developer Info": "개발자 정보",
    "User Guide": "사용자 설명서",
    "Support e-mail": "지원 이메일",
    "Our Website": "우리의 웹 사이트",
    "App Review": "앱 검토",
    "Enjoying App? Leave us a review in the App Market.": "앱 즐기기? App Market에서 리뷰를 남겨주세요 . ",
    "Review Us": "검토하기",
    "Connect With Us": "우리와 접촉",
    "What's your email?": "귀하의 이메일은 무엇입니까? ",
    "Invalid email address!": "잘못된 이메일 주소입니다! ",
    "Comments": "코멘트",
    "We'd love to hear from you. Send us a message.": "우리는 당신의 의견을 듣고 싶습니다. 우리에게 메시지를 보내십시오. ",
    "Message must be at least 5 characters long": "메시지 길이는 5 자 이상이어야합니다.",
    "Send": "보내다",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "사용자가 캘린더보기간에 전환 할 수있게하려면이 옵션을 활성화하고 표시 할보기를 선택하십시오. ",
    "Main": "본관",
    "Localize": "지역화",
    "Settings": "설정",
    "Layouts": "레이아웃",
    "Advanced": "많은",
    "Design": "디자인",
    "Support": "지원하다",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "모든 로컬 설정은 사용자의 언어에 따라 (자동으로) 설정됩니다. 언어가 목록에 있으면이 섹션을 사용자 정의 할 필요가 없습니다.",
    "Date Format":"날짜 형식",
    "Time Format":"시간 형식",
    "Text Direction":"텍스트 방향",
    "Left to Right":"왼쪽에서 오른쪽으로",
    "Right to Left":"오른쪽에서 왼쪽으로",
    "Week Starts On":"주 시작",
    "Agenda Style":"아젠다 스타일",
    "Classic":"권위 있는",
    "Modern":"현대",
    "Agenda Header":"아젠다 헤더",
    "Upcoming Events":"다가오는 이벤트",
    "Agenda Event Limit":"아젠다 이벤트 제한",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"지금 업그레이드하고 더 많은 기능을 사용하고 APP을 완전히 즐기십시오!",
    "Upgrade Now":"지금 업그레이드",
    "Hosting events that last all day? This lets you show them on your calendar.":"하루 종일 지속되는 행사를 주최합니까? 캘린더에 표시 할 수 있습니다.",
    "24 hours":"24 시간",
    "Sat": "토요일",
    "Sun": "일요일",
    "Mon": "월요일",
    "Default": "태만",
    "Select custom design style for your calendar.": "캘린더에 대한 사용자 정의 디자인 스타일을 선택하십시오.",
    "Style": "스타일",
    "Styles and Colors": "스타일과 색상",
    "Calendar Name":"캘린더 이름",
    "Write your Calendar name here":"여기에 캘린더 이름을 작성하십시오",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"사용자에게는 보이지 않습니다. 붐 캘린더 동기화 기능을 사용할 때 캘린더를 구별 할 수 있도록 이름을 설정하십시오.",
    "General Info" : "일반 정보",
    "Venue" : "장소",
    "Organizer"  : "조직자"
}

export default ko;
