let lv = {
    "Language": "Valoda",
    "Show Time Zone": "Rādīt laika joslu",
    "Custom Local Settings": "Pielāgoti vietējie iestatījumi",
    "Add and showcase events on your site using a beautiful calendar.": "Pievienojiet un demonstrējiet notikumus savā vietnē, izmantojot skaistu kalendāru . ",
    "Week Days": "Nedēļas dienas",
    "Manage Events": "Pārvaldīt pasākumus",
    "General": "Vispārīgi",
    "Layout Picker": "Izkārtojuma atlasītājs",
    "Month": "Mēnesis",
    "Monthly": "Mēneša",
    "Week": "Nedēļa",
    "Weekly": "Iknedēļas",
    "Day": "Diena",
    "Daily": "Katru dienu",
    "Agenda": "Darba kārtība",
    "Navigation Buttons": "Navigācijas pogas",
    "Today": "Šodien",
    "Week numbers": "Nedēļas numuri",
    "Include Weekends": "Iekļaut nedēļas nogales",
    "All-day": "Visu dienu",
    "All Day": "Visu dienu",
    "Label": "Etiķete",
    "Fit to Height": "Fit to Height",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "Lai iestatītu lietotņu proporcijas, manuāli jāatspējo šī opcija un jāmaina kalendāra lielums redaktorā. ",
    "Default Layout": "Noklusētais izkārtojums",
    "Monthly view": "Mēneša skats",
    "Weekly and Daily view": "Nedēļas un dienas skats",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Varat sniegt apmeklētājiem konsekventāku pieredzi, parādot vienādu nedēļu skaitu ( 6) vienlaikus.",
    "Fixed Weekly Layout": "Fiksēts nedēļas izkārtojums",
    "back": " atpakaļ ",
    "Row": "Rinda",
    "Hours in Weekly View": "Stundas nedēļas skatījumā",
    "Hours in Daily View": "Stundas ikdienas skatījumā",
    "Start": "Sākt",
    "End": "Beigas",
    "At This Hour": "Šajā stundā",
    "Add to": "Pievienot",
    "Button": "Poga",
    "Buttons": "Pogas",
    "Sunday": "Svētdiena",
    "Monday": "Pirmdiena",
    "Tuesday": "Otrdiena",
    "Wednesday": "Trešdiena",
    "Thursday": " Ceturtdiena ",
    "Friday": "Piektdiena",
    "Saturday": "Sestdiena",
    "Default Date": "Noklusējuma datums",
    "year": " gads ",
    "month": " mēnesis ",
    "days": " dienas ",
    "ago": " pirms ",
    "ahead": " priekšā ",
    "Yesterday": "Vakar",
    "Today": "Šodien",
    "Tomorrow": "Rīt",
    "Custom": "Pielāgots",
    "Set Daily Rows Limit": "Iestatīt ikdienas rindu limitu",
    "Set Proportions": "Iestatīt proporcijas",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Atļaut apmeklētājam pievienot notikumu vietējiem calnedars , Google, Yahoo, Outlook, ICalendar . ",
    "Container": "Konteiners",
    "Background": "Fons",
    "Container Background": "Konteinera fons",
    "Container Borders": "Konteineru robežas",
    "Calendar": "Kalendārs",
    "Event Info Tooltip": "Pasākuma informācijas rīka padoms",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "Kad cilvēki virzās virs kursora, viņi rīka padomā redzēs visu informāciju par to. ",
    "Event Info Window": "Pasākuma informācijas logs",
    "This is the full information window that opens when someone clicks on the event.": "Šis ir pilns informācijas logs, kas tiek atvērts, kad kāds noklikšķina uz notikuma. ",
    "Use Gradient": "Izmantojiet gradientu",
    "Vertical": "Vertikāls",
    "Horizontal": "Horizontāls",
    "First": "Pirmais",
    "Second": "Otrais",
    "diagonal": " pa diagonāli ",
    "Radial": "Radiāls",
    "Select option": "Atlasīt opciju",
    "Solid": "Ciets",
    "Dotted": "Punktēts",
    "Dashed": "Dashed",
    "Double": "Double",
    "Border Radius": "Robežas rādiuss",
    "Padding": "Polsterējums",
    "Date Header": "Datuma galvene",
    "Event Default Color": "Notikuma noklusējuma krāsa",
    "Days of Week": "Nedēļas dienas",
    "Days of Week Background": "Nedēļas dienu fons",
    "Date": "Datums",
    "Event Title": "Pasākuma nosaukums",
    "Highlight today": "Izcelt šodien",
    "Highlight Color": "Izcelt krāsu",
    "Hide": "Slēpt",
    "Calendar Border Color": "Kalendāra apmales krāsa",
    "Calendar Border Width": "Kalendāra robežas platums",
    "Calendar Border Style": "Kalendāra apmales stils",
    "Font Color": "Fonta krāsa",
    "Event Background": "Pasākuma fons",
    "Card Date Color": "Kartes datuma krāsa",
    "Title Font": "Nosaukuma fonts",
    "Date Font": "Datuma fonts",
    "Description Font": "Apraksts fonts",
    "Button Background": "Pogas fons",
    "Button Text": "Pogas teksts",
    "Border Color": "Apmales krāsa",
    "Border Width": "Robežas platums",
    "Border Type": "Robežas tips",
    "Title": "Virsraksts",
    "Description": "Apraksts",
    "Background Color": "Fona krāsa",
    "Divider": "Dalītājs",
    "Event Details Font": "Pasākuma detaļu fonts",
    "Website Link Color": "Vietnes saites krāsa",
    "Developer Info": "Informācija par izstrādātāju",
    "User Guide": "Lietotāja rokasgrāmata",
    "Support e-mail": "Atbalsta e-pasts",
    "Our Website": "Mūsu vietne",
    "App Review": "Lietotnes pārskats",
    "Enjoying App? Leave us a review in the App Market.": "Patīk lietotne? Atstājiet mums pārskatu App Market. ",
    "Review Us": "Pārskatiet mūs",
    "Connect With Us": "Sazinieties ar mums",
    "What's your email?": "Kāds ir jūsu e-pasts? ",
    "Invalid email address!": "Nederīga e-pasta adrese! ",
    "Comments": "Komentāri",
    "We'd love to hear from you. Send us a message.": "Mēs labprāt dzirdētu no jums. Nosūtiet mums ziņojumu. ",
    "Message must be at least 5 characters long": "Ziņojumam jābūt vismaz 5 rakstzīmju garam",
    "Send": "Sūtīt",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Ja vēlaties ļaut lietotājam pārslēgties starp kalendāra skatiem, iespējojiet šo opciju un izvēlieties skatus, kurus vēlaties parādīt. ",
    "Main": "Galvenais",
    "Localize": "Lokalizēt",
    "Settings": "Iestatījumi",
    "Layouts": "Izkārtojumi",
    "Advanced": "Uzlabots",
    "Design": "Dizains",
    "Support": "Atbalsts",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Visi vietējie iestatījumi (automātiski) ir balstīti uz jūsu valodu. Ja jūsu valoda ir sarakstā, šī sadaļa nav jāpielāgo.",
    "Date Format":"Datuma formāts",
    "Time Format":"Laika formāts",
    "Text Direction":"Teksta virziens",
    "Left to Right":"No kreisās uz labo",
    "Right to Left":"Pa labi no kreisās",
    "Week Starts On":"Nedēļa sākas",
    "Agenda Style":"Darba kārtības stils",
    "Classic":"Klasika",
    "Modern":"Mūsdienu",
    "Agenda Header":"Darba kārtības galvene",
    "Upcoming Events":"Gaidāmie notikumi",
    "Agenda Event Limit":"Darba kārtības notikumu limits",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"Jauniniet tagad un iegūstiet daudz vairāk funkciju un pilnībā izbaudiet savu lietotni!",
    "Upgrade Now":"Uzlabot tagad",
    "Hosting events that last all day? This lets you show them on your calendar.":"Notikumi, kas ilgst visu dienu? Tas ļauj jums tos parādīt kalendārā.",
    "24 hours":"24 stundas",
    "Sun": "Svēt",
    "Mon": "Pirm",
    "Sat": "Sest",
    "Default": "Noklusējums",
    "Select custom design style for your calendar.": "Atlasiet sava kalendāra pielāgoto noformējuma stilu.",
    "Style": "Stils",
    "Styles and Colors": "Stili un krāsas",
    "Calendar Name":"Kalendāra nosaukums",
    "Write your Calendar name here":"Šeit ierakstiet kalendāra vārdu",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"Tas jūsu lietotājiem nav redzams. Iestatiet nosaukumus, lai atšķirtu kalendārus, kad izmantojat Boom Calendar Sync funkciju.",
    "General Info" : "Vispārīga informācija",
    "Venue" : "Norises vieta",
    "Organizer"  : "Organizators"

}

export default lv;
