let nl = {
    "Language": "Taal",
    "Show Time Zone": "Tijdzone Tonen",
    "Custom Local Settings": "Aangepaste Lokale Instellingen",
    "Add and showcase events on your site using a beautiful calendar.": "Voeg evenementen toe aan uw pagina met behulp van een mooie kalender . ",
    "Week Days": "Dagen van de Week",
    "Manage Events": "Beheer Evenementen",
    "General": "Algemeen",
    "Layout Picker": "Kies Layout",
    "Month": "Maand",
    "Monthly": "Per Maand",
    "Week": "Week",
    "Weekly": "Per Week",
    "Day": "Dag",
    "Daily": "Per Dag",
    "Agenda": "Agenda",
    "Navigation Buttons": "Navigatie Knoppen",
    "Today": "Vandaag",
    "Week numbers": "Weeknummers",
    "Include Weekends": "Inclusief Weekend",
    "All-day": "De hele dag",
    "All Day": "De hele dag",
    "Label": "Benoemen",
    "Fit to Height": "Aanpassen aan Hoogte",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "Als u app-verhoudingen wilt instellen, schakelt u deze optie uit en wijzigt u de grootte van Kalender in Editor. ",
    "Default Layout": "Standaard Opmaak",
    "Monthly view": "per Maand",
    "Weekly and Daily view": "Wekelijkse en Dagelijkse overzicht",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "U kunt bezoekers een meer consistente ervaring geven door hetzelfde aantal weken ( 6) tegelijkertijd weer te geven.",
    "Fixed Weekly Layout": "Vaste Weekindeling",
    "back": " terug ",
    "Row": "Rij",
    "Hours in Weekly View": "Uren per Week",
    "Hours in Daily View": "Uren per Dag",
    "Start": "Begin",
    "End": "Eind",
    "At This Hour": "Tijdstip",
    "Add to": "Voeg toe",
    "Button": "Knop",
    "Buttons": "Toetsen",
    "Sunday": "Zondag",
    "Monday": "Maandag",
    "Tuesday": "Dinsdag",
    "Wednesday": "Woensdag",
    "Thursday": " Donderdag ",
    "Friday": "Vrijdag",
    "Saturday": "Zaterdag",
    "Default Date": "Standaard Datum",
    "year": " jaar ",
    "month": " maand ",
    "days": " dagen ",
    "ago": " geleden ",
    "ahead": " vooruit ",
    "Yesterday": "Gisteren",
    "Today": "Vandaag",
    "Tomorrow": "Morgen",
    "Custom": "Aangepast",
    "Set Daily Rows Limit": "Rijenlimiet Dagen Instellen",
    "Set Proportions": "Eigenschappen Instellen",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Toestaan dat bezoeker evenement aan lokale Agenda's toevoegt , Google, Yahoo, Outlook, ICalendar . ",
    "Container": "Kader",
    "Background": "Achtergrond",
    "Container Background": "Achtergrond Kader",
    "Container Borders": "Randen Kader",
    "Calendar": "Kalender",
    "Event Info Tooltip": "Event Info Tooltip",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "Wanneer mensen boven een evenement hangen, zien ze alle info erover in een tooltip. ",
    "Event Info Window": "Event Info Window",
    "This is the full information window that opens when someone clicks on the event.": "Dit is het volledige informatievenster dat opent, wanneer men op het evenement klikt. ",
    "Use Gradient": "Gebruik Gradient",
    "Vertical": "Verticaal",
    "Horizontal": "Horizontaal",
    "First": "Eerste",
    "Second": "Tweede",
    "diagonal": " Diagonaal ",
    "Radial": "Radiaal",
    "Select option": "Selecteer optie",
    "Solid": "Solide",
    "Dotted": "Gestippeld",
    "Dashed": "Gestreept",
    "Double": "Dubbel",
    "Border Radius": "Rand Radius",
    "Padding": "Vulling",
    "Date Header": "Datum Koptekst",
    "Event Default Color": "Standaardkleur Evenement",
    "Days of Week": "Dagen van de Week",
    "Days of Week Background": "Achtergrond Dagen van de Week",
    "Date": "Datum",
    "Event Title": "Titel van Evenement",
    "Highlight today": "Markeer Vandaag",
    "Highlight Color": "Markeer Kleur",
    "Hide": "Verbergen",
    "Calendar Border Color": "Randkleur Kalender",
    "Calendar Border Width": "Randbreedte Kalender",
    "Calendar Border Style": "Randstijl Kalender",
    "Font Color": "Letterkleur",
    "Event Background": "Achtergrond Activiteit",
    "Card Date Color": "Kaart Datum kleur",
    "Title Font": "Titel Lettertype",
    "Date Font": "Datum Lettertype",
    "Description Font": "Omschrijving Lettertype",
    "Button Background": "Knop Achtergrond",
    "Button Text": "Knop Tekst",
    "Border Color": "Randkleur",
    "Border Width": "Grensbreedte",
    "Border Type": "Rand Type",
    "Title": "Titel",
    "Description": "Omschrijving",
    "Background Color": "Achtergrond Kleur",
    "Divider": "Verdeler",
    "Event Details Font": "Evenement Details Lettertype",
    "Website Link Color": "Website Link Kleur",
    "Developer Info": "Info ontwikkelaar",
    "User Guide": "Gebruikershandleiding",
    "Support e-mail": "Ondersteuning e-mail",
    "Our Website": "Onze website",
    "App Review": "App Beoordeling",
    "Enjoying App? Leave us a review in the App Market.": "Blij met de app? Schrijf een beoordeling in de App-markt. ",
    "Review Us": "Beoordeel ons",
    "Connect With Us": "Bericht sturen",
    "What's your email?": "Wat is uw e-mail? ",
    "Invalid email address!": "Ongeldig e-mailadres! ",
    "Comments": "Reacties",
    "We'd love to hear from you. Send us a message.": "Wij horen graag van u. Stuur ons een bericht. ",
    "Message must be at least 5 characters long": "Bericht moet minimaal 5 tekens lang zijn",
    "Send": "Verzenden",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Als u de gebruiker wilt laten schakelen tussen agendaweergaven, schakelt u deze optie in en kiest u de weergaven die u wilt zien. ",
    "Main": "Hoofd",
    "Localize": "Lokaliseren",
    "Settings": "Instellingen",
    "Layouts": "Opmaak",
    "Advanced": "Geavanceerd",
    "Design": "Ontwerp",
    "Support": "Hulp",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Alle lokale instellingen zijn (automatisch) gebaseerd op uw taal. Als uw taal in de lijst staat, hoeft u dit gedeelte niet aan te passen.",
    "Date Format":"Datum",
    "Time Format":"Tijd",
    "Text Direction":"Tekstrichting",
    "Left to Right":"van Links naar Rechts",
    "Right to Left":"van Rechts naar Links",
    "Week Starts On":"Week Begint Op",
    "Agenda Style":"Agendastijl",
    "Classic":"Klassiek",
    "Modern":"Modern",
    "Agenda Header":"Koptekst Agenda",
    "Upcoming Events":"Aankomende Evenementen",
    "Agenda Event Limit":"Evenement Limiet Instellen",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"Upgrade nu en krijg veel meer functies en geniet volop van uw APP!",
    "Upgrade Now":"Nu upgraden",
    "Hosting events that last all day? This lets you show them on your calendar.":"Organiseert u evenementen die de hele dag duren? Hiermee kunt u ze in uw agenda weergeven.",
    "24 hours":"24 uur",
    "Sat": "Zat",
    "Sun": "Zon",
    "Mon": "Maan",
    "Default": "Standaard",
    "Select custom design style for your calendar.": "Selecteer een aangepaste ontwerpstijl voor uw kalender.",
    "Style": "Stijl",
    "Styles and Colors": "Stijlen en kleuren",
    "Calendar Name":"Naam van agenda",
    "Write your Calendar name here":"Schrijf hier uw agendanaam",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"Dit is niet zichtbaar voor uw gebruikers. Stel namen in om uw agenda's te onderscheiden wanneer u de Boom Calendar Sync-functie gebruikt.",
    "General Info" : "Algemene informatie",
    "Venue" : "Evenementenlocatie",
    "Organizer"  : "Organisator"

}

export default nl;
