let no = {
    "Language": "Språk",
    "Show Time Zone": "Vis tidssone",
    "Custom Local Settings": "Tilpassede lokale innstillinger",
    "Add and showcase events on your site using a beautiful calendar.": "Legg til og vis hendelser på nettstedet ditt ved hjelp av en vakker kalender . ",
    "Week Days": "Ukedager",
    "Manage Events": "Administrer hendelser",
    "General": "Generell",
    "Layout Picker": "Layout Picker",
    "Month": "Måned",
    "Monthly": "Månedlig",
    "Week": "Uke",
    "Weekly": "Ukentlig",
    "Day": "Dag",
    "Daily": "Daglig",
    "Agenda": "Dagsorden",
    "Navigation Buttons": "Navigasjonsknapper",
    "Today": "I dag",
    "Week numbers": "Ukenummer",
    "Include Weekends": "Inkluder helger",
    "All-day": "Hele dagen",
    "All Day": "Hele dagen",
    "Label": "Merkelapp",
    "Fit to Height": "Fit to Height",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "Slik angir du app-proporsjoner manuelt deaktiverer dette alternativet og endrer størrelse på kalender i Editor. ",
    "Default Layout": "Standardoppsett",
    "Monthly view": "Månedsvisning",
    "Weekly and Daily view": "Ukentlig og daglig visning",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Du kan gi besøkende en mer konsistent opplevelse ved å vise samme antall uker ( 6) om gangen.",
    "Fixed Weekly Layout": "Fast ukesoppsett",
    "back": " tilbake ",
    "Row": "Rad",
    "Hours in Weekly View": "Timer i ukesvisning",
    "Hours in Daily View": "Timer i daglig visning",
    "Start": "Start",
    "End": "Slutt",
    "At This Hour": "På denne timen",
    "Add to": "Legge til",
    "Button": "Knapp",
    "Buttons": "Knapper",
    "Sunday": "Søndag",
    "Monday": "Mandag",
    "Tuesday": "Tirsdag",
    "Wednesday": "Onsdag",
    "Thursday": " Torsdag ",
    "Friday": "Fredag",
    "Saturday": "Lørdag",
    "Default Date": "Standard dato",
    "year": " år ",
    "month": " måned ",
    "days": " dager ",
    "ago": " siden ",
    "ahead": " fremover ",
    "Yesterday": "I går",
    "Today": "I dag",
    "Tomorrow": "I morgen",
    "Custom": "Tilpasset",
    "Set Daily Rows Limit": "Angi grense for daglige rader",
    "Set Proportions": "Angi proporsjoner",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Tillat besøkende å legge til hendelser i lokale kalendere , Google, Yahoo, Outlook, ICalendar . ",
    "Container": "Container",
    "Background": "Bakgrunn",
    "Container Background": "Beholder bakgrunn",
    "Container Borders": "Beholdergrenser",
    "Calendar": "Kalender",
    "Event Info Tooltip": "Verktøytips for hendelsesinfo",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "Når folk svever over et arrangement, vil de se all informasjonen om det i en verktøytips. ",
    "Event Info Window": "Vinduet med hendelsesinfo",
    "This is the full information window that opens when someone clicks on the event.": "Dette er det fullstendige informasjonsvinduet som åpnes når noen klikker på hendelsen. ",
    "Use Gradient": "Bruk gradient",
    "Vertical": "Vertical",
    "Horizontal": "Horisontal",
    "First": "Først",
    "Second": "Sekund",
    "diagonal": " diagonal ",
    "Radial": "Radial",
    "Select option": "Velg alternativ",
    "Solid": "Fast",
    "Dotted": "Prikket",
    "Dashed": "Stiplet",
    "Double": "Dobbelt",
    "Border Radius": "Border Radius",
    "Padding": "Padding",
    "Date Header": "Datohode",
    "Event Default Color": "Standardfarge på arrangement",
    "Days of Week": "Dager i uken",
    "Days of Week Background": "Days of Week bakgrunn",
    "Date": "Dato",
    "Event Title": "Eventtittel",
    "Highlight today": "Uthev i dag",
    "Highlight Color": "Uthev farge",
    "Hide": "Gjemme seg",
    "Calendar Border Color": "Kalenderramme farge",
    "Calendar Border Width": "Kalendergrensebredde",
    "Calendar Border Style": "Kalendergrensestil",
    "Font Color": "Skriftfarge",
    "Event Background": "Hendelsesbakgrunn",
    "Card Date Color": "Farge på kortdato",
    "Title Font": "Tittelfont",
    "Date Font": "Datoskrift",
    "Description Font": "Beskrivelse Font",
    "Button Background": "Knappbakgrunn",
    "Button Text": "Knapptekst",
    "Border Color": "Grensefarge",
    "Border Width": "Border Width",
    "Border Type": "Grensetype",
    "Title": "Tittel",
    "Description": "Beskrivelse",
    "Background Color": "Bakgrunnsfarge",
    "Divider": "Deler",
    "Event Details Font": "Fontdetaljer for hendelsesdetaljer",
    "Website Link Color": "Nettstedslinkfarge",
    "Developer Info": "Utviklerinfo",
    "User Guide": "Brukerhåndboken",
    "Support e-mail": "Støtte e-post",
    "Our Website": "Vår nettside",
    "App Review": "Appanmeldelse",
    "Enjoying App? Leave us a review in the App Market.": "Nyter appen? Gi oss en anmeldelse i appmarkedet. ",
    "Review Us": "Gjennomgå oss",
    "Connect With Us": "Koble til oss",
    "What's your email?": "Hva er e-postmeldingen din? ",
    "Invalid email address!": "Ugyldig e-postadresse! ",
    "Comments": "Kommentarer",
    "We'd love to hear from you. Send us a message.": "Vi vil gjerne høre fra deg. Send oss ​​en melding. ",
    "Message must be at least 5 characters long": "Meldingen må være minst 5 tegn lang",
    "Send": "Sende",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Hvis du vil la brukeren bytte mellom kalendervisninger, aktiverer du dette alternativet og velger visningene du vil vise. ",
    "Main": "Hoved",
    "Localize": "Lokal",
    "Settings": "innstillinger",
    "Layouts": "oppsett",
    "Advanced": "Avansert",
    "Design": "Design",
    "Support": "Brukerstøtte",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Alle lokale innstillinger er (automatisk) basert på språket ditt. Hvis språket ditt er på listen, er det ikke nødvendig å tilpasse denne delen.",
    "Date Format":"Datoformat",
    "Time Format":"Tidsformat",
    "Text Direction":"Tekstretning",
    "Left to Right":"Venstre til høyre",
    "Right to Left":"Høyre til venstre",
    "Week Starts On":"Uken starter",
    "Agenda Style":"Agenda Style",
    "Classic":"Classic",
    "Modern":"Moderne",
    "Agenda Header":"Agenda Header",
    "Upcoming Events":"Kommende arrangementer",
    "Agenda Event Limit":"Agenda Event Limit",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"Oppgrader nå og få mange flere funksjoner og nyt appen din i sin helhet!",
    "Upgrade Now":"Oppgrader nå",
    "Hosting events that last all day? This lets you show them on your calendar.":"Hosting av arrangementer som varer hele dagen? Dette lar deg vise dem i kalenderen din.",
    "24 hours":"24 timer",
    "Sun": "Søn",
    "Mon": "Man",
    "Sat": "Lør",
    "Default": "Misligholde",
    "Select custom design style for your calendar.": "Velg tilpasset designstil for kalenderen.",
    "Style": "Stil",
    "Styles and Colors": "Stiler og farger",
    "Calendar Name":"Kalendernavn",
    "Write your Calendar name here":"Skriv kalendernavnet ditt her",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"Dette er ikke synlig for brukerne dine. Angi navn for å differensiere kalenderne dine når du bruker Boom Calendar Sync-funksjonen.",
    "General Info" : "Generell info",
    "Venue" : "Spillested",
    "Organizer"  : "Planlegger"
};

export default no;
