let pl = {
    "Language": "Język",
    "Show Time Zone": "Pokaż strefę czasową",
    "Custom Local Settings": "Niestandardowe ustawienia lokalne",
    "Add and showcase events on your site using a beautiful calendar.": "Dodaj i pokaż wydarzenia w swojej witrynie za pomocą pięknego kalendarza . ",
    "Week Days": "Dni tygodnia",
    "Manage Events": "Zarządzaj wydarzeniami",
    "General": "Generał",
    "Layout Picker": "Wybór układu",
    "Month": "Miesiąc",
    "Monthly": "Miesięczny",
    "Week": "Tydzień",
    "Weekly": "Co tydzień",
    "Day": "Dzień",
    "Daily": "Codziennie",
    "Agenda": "Program",
    "Navigation Buttons": "Przyciski nawigacyjne",
    "Today": "Dzisiaj",
    "Week numbers": "Numery tygodniowe",
    "Include Weekends": "Dołącz weekendy",
    "All-day": "Cały dzień",
    "All Day": "Cały dzień",
    "Label": "Etykieta",
    "Fit to Height": "Dopasuj do wysokości",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "Aby ustawić proporcje App manully wyłączyć tę opcję i rozmiaru kalendarz w edytorze. ",
    "Default Layout": "Domyślny układ",
    "Monthly view": "Widok miesięczny",
    "Weekly and Daily view": "Widok tygodniowy i dzienny",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Możesz zapewnić odwiedzającym bardziej spójne wrażenia, pokazując tę ​​samą liczbę tygodni ( 6) naraz",
    "Fixed Weekly Layout": "Naprawiono układ tygodniowy",
    "back": " powrót ",
    "Row": "Rząd",
    "Hours in Weekly View": "Godziny w widoku tygodniowym",
    "Hours in Daily View": "Godziny w widoku dziennym",
    "Start": "Początek",
    "End": "Koniec",
    "At This Hour": "O tej godzinie",
    "Add to": "Dodać do",
    "Button": "Przycisk",
    "Buttons": "Guziki",
    "Sunday": "Niedziela",
    "Monday": "Poniedziałek",
    "Tuesday": "Wtorek",
    "Wednesday": "Środa",
    "Thursday": " Czwartek ",
    "Friday": "Piątek",
    "Saturday": "Sobota",
    "Default Date": "Data domyślna",
    "year": " rok ",
    "month": " miesiąc ",
    "days": " dni ",
    "ago": " temu ",
    "ahead": " naprzód ",
    "Yesterday": "Wczoraj",
    "Today": "Dzisiaj",
    "Tomorrow": "Jutro",
    "Custom": "Zwyczaj",
    "Set Daily Rows Limit": "Ustaw limit dzienny wierszy",
    "Set Proportions": "Ustaw proporcje",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Pozwól odwiedzającym dodawać wydarzenia do lokalnych Calnedars , Google, Yahoo, Outlook, ICalendar . ",
    "Container": "Pojemnik",
    "Background": "Tło",
    "Container Background": "Tło pojemnika",
    "Container Borders": "Granice kontenerów",
    "Calendar": "Kalendarz",
    "Event Info Tooltip": "Etykieta informacji o wydarzeniu",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "Gdy ludzie najeżdżają na zdarzenie, zobaczą wszystkie informacje o nim w podpowiedzi. ",
    "Event Info Window": "Okno informacji o wydarzeniu",
    "This is the full information window that opens when someone clicks on the event.": "To jest pełne okno informacyjne, które otwiera się, gdy ktoś kliknie wydarzenie. ",
    "Use Gradient": "Użyj gradientu",
    "Vertical": "Pionowy",
    "Horizontal": "Poziomy",
    "First": "Pierwszy",
    "Second": "Druga",
    "diagonal": " przekątna ",
    "Radial": "Promieniowy",
    "Select option": "Wybierz opcję",
    "Solid": "Solidny",
    "Dotted": "Kropkowany",
    "Dashed": "Przerywane",
    "Double": "Podwójnie",
    "Border Radius": "Promień graniczny",
    "Padding": "Wyściółka",
    "Date Header": "Nagłówek daty",
    "Event Default Color": "Domyślny kolor zdarzenia",
    "Days of Week": "Dni tygodnia",
    "Days of Week Background": "Tło dni tygodnia",
    "Date": "Data",
    "Event Title": "Tytuł wydarzenia",
    "Highlight today": "Podświetl dzisiaj",
    "Highlight Color": "Podświetlony kolor",
    "Hide": "Ukryć",
    "Calendar Border Color": "Kolor obramowania kalendarza",
    "Calendar Border Width": "Szerokość obramowania kalendarza",
    "Calendar Border Style": "Styl obramowania kalendarza",
    "Font Color": "Kolor czcionki",
    "Event Background": "Tło wydarzenia",
    "Card Date Color": "Kolor daty karty",
    "Title Font": "Czcionka tytułu",
    "Date Font": "Czcionka daty",
    "Description Font": "Czcionka opisu",
    "Button Background": "Tło przycisku",
    "Button Text": "Przycisk tekstowy",
    "Border Color": "Kolor ramki",
    "Border Width": "Szerokość granicy",
    "Border Type": "Typ obramowania",
    "Title": "Tytuł",
    "Description": "Opis",
    "Background Color": "Kolor tła",
    "Divider": "Rozdzielacz",
    "Event Details Font": "Czcionka szczegółów wydarzenia",
    "Website Link Color": "Kolor linku do witryny",
    "Developer Info": "Informacje dla programistów",
    "User Guide": "Podręcznik użytkownika",
    "Support e-mail": "Wsparcie e-mail",
    "Our Website": "Nasza strona internetowa",
    "App Review": "Przegląd aplikacji",
    "Enjoying App? Leave us a review in the App Market.": "Korzystając z aplikacji? Zostaw nam recenzję na App Market. ",
    "Review Us": "Sprawdź nas",
    "Connect With Us": "Połącz się z nami",
    "What's your email?": "Jaki jest twój e-mail? ",
    "Invalid email address!": "Nieprawidłowy adres e-mail! ",
    "Comments": "Komentarze",
    "We'd love to hear from you. Send us a message.": "Chcielibyśmy usłyszeć od ciebie. Wyślij nam wiadomość. ",
    "Message must be at least 5 characters long": "Wiadomość musi mieć co najmniej 5 znaków",
    "Send": "Wysłać",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Jeśli chcesz zezwolić użytkownikowi na przełączanie się między widokami kalendarza, włącz tę opcję i wybierz widoki, które chcesz pokazać. ",
    "Main": "Główny",
    "Localize": "Zlokalizować",
    "Settings": "Ustawienia",
    "Layouts": "Układy",
    "Advanced": "Zaawansowane",
    "Design": "Projekt",
    "Support": "Wsparcie",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Wszystkie lokalne ustawienia są (automatycznie) oparte na twoim języku. Jeśli Twój język jest na liście, nie ma potrzeby dostosowywania tej sekcji.",
    "Date Format":"Format daty",
    "Time Format":"Format czasu",
    "Text Direction":"Kierunek tekstu",
    "Left to Right":"Z lewej na prawą",
    "Right to Left":"Od prawej do lewej",
    "Week Starts On":"Tydzień zaczyna się od",
    "Agenda Style":"Styl agendy",
    "Classic":"Klasyczny",
    "Modern":"Nowoczesny",
    "Agenda Header":"Nagłówek agendy",
    "Upcoming Events":"nadchodzące wydarzenia",
    "Agenda Event Limit":"Limit zdarzeń agendy",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"Zaktualizuj teraz i uzyskaj o wiele więcej funkcji i ciesz się aplikacją w całości!",
    "Upgrade Now":"Ulepsz teraz",
    "Hosting events that last all day? This lets you show them on your calendar.":"Prowadzisz wydarzenia trwające cały dzień? To pozwala pokazać je w kalendarzu.",
    "24 hours":"24 godziny",
    "Sat": "Sob",
    "Sun": "Nie",
    "Mon": "Pon",
    "Default": "Domyślna",
    "Select custom design style for your calendar.": "Wybierz niestandardowy styl projektowania swojego kalendarza.",
    "Style": "Styl",
    "Styles and Colors":"Style i kolory",
    "Calendar Name":"Nazwa kalendarza",
    "Write your Calendar name here":"Wpisz tutaj swoją nazwę kalendarza",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"Nie jest to widoczne dla użytkowników. Ustaw nazwy, aby rozróżnić kalendarze podczas korzystania z funkcji synchronizacji kalendarza Boom.",
    "General Info" : "Ogólne informacje",
    "Venue" : "Miejsce wydarzenia",
    "Organizer"  : "Organizator"

};

export default pl;
