let pt = {
    "Language": "Língua",
    "Show Time Zone": "Mostrar fuso horário",
    "Custom Local Settings": "Configurações locais personalizadas",
    "Add and showcase events on your site using a beautiful calendar.": "Adicione e exiba eventos em seu site usando um calendário bonito . ",
    "Week Days": "Dias úteis",
    "Manage Events": "Gerenciar Eventos",
    "General": "Geral",
    "Layout Picker": "Selecionador de Layout",
    "Month": "Mês",
    "Monthly": "Por mês",
    "Week": "Semana",
    "Weekly": "Semanal",
    "Day": "Dia",
    "Daily": "Diariamente",
    "Agenda": "Agenda",
    "Navigation Buttons": "Botões de Navegação",
    "Today": "Hoje",
    "Week numbers": "Números da semana",
    "Include Weekends": "Incluir fins de semana",
    "All-day": "Dia todo",
    "All Day": "Dia todo",
    "Label": "Rótulo",
    "Fit to Height": "Ajustar à altura",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "Para definir proporções App manully desabilitar essa opção e redimensionar Calendário no Editor. ",
    "Default Layout": "Layout padrão",
    "Monthly view": "Visualização mensal",
    "Weekly and Daily view": "Vista semanal e diária",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Você pode oferecer aos visitantes uma experiência mais consistente, mostrando o mesmo número de semanas ( 6) de cada vez.",
    "Fixed Weekly Layout": "Layout Semanal Fixo",
    "back": "de volta ",
    "Row": "Linha",
    "Hours in Weekly View": "Horas na Vista Semanal",
    "Hours in Daily View": "Horas na visualização diária",
    "Start": "Começar",
    "End": "Fim",
    "At This Hour": "Nesta hora",
    "Add to": "Adicionar à",
    "Button": "Botão",
    "Buttons": "Botões",
    "Sunday": "Domingo",
    "Monday": "Segunda-feira",
    "Tuesday": "Terça",
    "Wednesday": "Quarta-feira",
    "Thursday": " Quinta-feira ",
    "Friday": "Sexta-feira",
    "Saturday": "Sábado",
    "Default Date": "Data padrão",
    "year": " ano ",
    "month": " mês ",
    "days": " dias ",
    "ago": " ago ",
    "ahead": " à frente ",
    "Yesterday": "Ontem",
    "Today": "Hoje",
    "Tomorrow": "Amanhã",
    "Custom": "Personalizadas",
    "Set Daily Rows Limit": "Definir Limite de Linhas Diárias",
    "Set Proportions": "Definir Proporções",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Permitir que o visitante adicione o evento aos Calendários locais , Google, Yahoo, Outlook, ICalendar . ",
    "Container": "Recipiente",
    "Background": "Fundo",
    "Container Background": "Fundo do recipiente",
    "Container Borders": "Fronteiras do contêiner",
    "Calendar": "Calendário",
    "Event Info Tooltip": "Event Info Tooltip",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "Quando as pessoas passam o mouse sobre um evento, elas verão todas as informações sobre ele em uma dica de ferramenta. ",
    "Event Info Window": "Janela de Informações do Evento",
    "This is the full information window that opens when someone clicks on the event.": "Esta é a janela de informações completa que se abre quando alguém clica no evento. ",
    "Use Gradient": "Use Gradient",
    "Vertical": "Vertical",
    "Horizontal": "Horizontal",
    "First": "Primeiro",
    "Second": "Segundo",
    "diagonal": " diagonal ",
    "Radial": "Radial",
    "Select option": "Selecionar opção",
    "Solid": "Sólido",
    "Dotted": "Pontilhado",
    "Dashed": "Tracejadas",
    "Double": "Em dobro",
    "Border Radius": "Raio da Borda",
    "Padding": "Preenchimento",
    "Date Header": "Data de cabeçalho",
    "Event Default Color": "Cor Padrão do Evento",
    "Days of Week": "Dias da semana",
    "Days of Week Background": "Dias de fundo da semana",
    "Date": "Encontro",
    "Event Title": "Título do evento",
    "Highlight today": "Destaque hoje",
    "Highlight Color": "Cor de destaque",
    "Hide": "Ocultar",
    "Calendar Border Color": "Calendar Border Color",
    "Calendar Border Width": "Largura do limite do calendário",
    "Calendar Border Style": "Estilo de borda do calendário",
    "Font Color": "Cor da fonte",
    "Event Background": "Antecedentes do Evento",
    "Card Date Color": "Cor da data do cartão",
    "Title Font": "Fonte do título",
    "Date Font": "Data da fonte",
    "Description Font": "Descrição da fonte",
    "Button Background": "Botão de fundo",
    "Button Text": "Botão de texto",
    "Border Color": "Cor da borda",
    "Border Width": "Largura da Fronteira",
    "Border Type": "Tipo de Borda",
    "Title": "Título",
    "Description": "Descrição",
    "Background Color": "Cor de fundo",
    "Divider": "Divisor",
    "Event Details Font": "Fonte de detalhes do evento",
    "Website Link Color": "Website Link Color",
    "Developer Info": "Informações do desenvolvedor",
    "User Guide": "Guia de usuario",
    "Support e-mail": "Suporte e-mail",
    "Our Website": "Nosso site",
    "App Review": "App Review",
    "Enjoying App? Leave us a review in the App Market.": "Desfrutando App? Deixe-nos um comentário no App Market. ",
    "Review Us": "Revise-nos",
    "Connect With Us": "Conecte-se conosco",
    "What's your email?": "Qual é o seu email? ",
    "Invalid email address!": "Endereço de email inválido! ",
    "Comments": "Comentários",
    "We'd love to hear from you. Send us a message.": "Gostaríamos muito de ouvir de você. Envie-nos uma mensagem. ",
    "Message must be at least 5 characters long": "A mensagem deve ter pelo menos 5 caracteres",
    "Send": "Mandar",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Se você quiser permitir que o usuário alterne entre exibições de calendário, ative esta opção e escolha as exibições que deseja exibir. ",
    "Main": "a Principal",
    "Localize": "Localizar",
    "Settings": "Definições",
    "Layouts": "Plano",
    "Advanced": "Avançado",
    "Design": "desenhar",
    "Support": "Apoio, suporte",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Todas as configurações locais são (automaticamente) baseadas no seu idioma. Se o seu idioma estiver na lista, não há necessidade de personalizar esta seção.",
    "Date Format":"Formato de data",
    "Time Format":"Formato de hora",
    "Text Direction":"Direção do texto",
    "Left to Right":"Esquerda para a direita",
    "Right to Left":"Direita para esquerda",
    "Week Starts On":"Semana começa em",
    "Agenda Style":"Agenda Style",
    "Classic":"Clássico",
    "Modern":"Moderno",
    "Agenda Header":"Cabeçalho da agenda",
    "Upcoming Events":"Próximos eventos",
    "Agenda Event Limit":"Limite do Evento da Agenda",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"Atualize agora e tenha muito mais recursos e aproveite seu aplicativo na íntegra!",
    "Upgrade Now":"Atualize agora",
    "Hosting events that last all day? This lets you show them on your calendar.":"Eventos de hospedagem que duram o dia todo? Isso permite que você os mostre no seu calendário.",
    "24 hours":"24 horas",
    "Sun": "Dom",
    "Mon": "Seg",
    "Sat": "Sáb",
    "Default": "Padrão",
    "Select custom design style for your calendar.":"Selecione o estilo de design personalizado para o seu calendário.",
    "Style":"Estilo",
    "Styles and Colors": "Estilos e cores",
    "Calendar Name":"Nome do calendário",
    "Write your Calendar name here":"Escreva aqui o nome do seu calendário",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"Isso não é visível para seus usuários. Defina nomes para diferenciar seus calendários ao usar a função Boom Calendar Sync.",
    "General Info" : "Informações gerais",
    "Venue" : "Local",
    "Organizer"  : "Organizador"

};

export default pt;
