let ru = {
    "Language": "Язык",
    "Show Time Zone": "Показать часовой пояс",
    "Custom Local Settings": "Пользовательские локальные настройки",
    "Add and showcase events on your site using a beautiful calendar.": 'Добавляйте и демонстрируйте события на своем сайте, используя красивый календарь.',
    "Week Days": 'Будние дни',
    "Manage Events": "Управление событиями",
    "General": "Генеральный",
    "Layout Picker": "Выбор макета",
    "Month": "Месяц",
    "Monthly": "Ежемесячно",
    "Week": "Неделя",
    "Weekly": "Еженедельно",
    "Day": "День",
    "Daily": "Ежедневно",
    "Agenda": "Повестка дня",
    "Navigation Buttons": "Кнопки навигации",
    "Today": "Сегодня",
    "Week numbers": "Номера недели",
    "Include Weekends": "Включить выходные",
    "All-day": "Весь день",
    "All Day": "Весь день",
    "Label": "Этикетка",
    "Fit to Height": "Подходит к высоте",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "Чтобы установить пропорции приложения, вручную отключите эту опцию и измените размер календаря в редакторе.",
    "Default Layout": "Макет по умолчанию",
    "Monthly view": "Ежемесячный просмотр",
    "Weekly and Daily view": "Еженедельный и ежедневный просмотр",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Вы можете дать посетителям более последовательный опыт, показывая одинаковое количество недель (6) за раз.",
    "Fixed Weekly Layout": "Фиксированный недельный макет",
    "back": "назад",
    "Row": "Строка",
    "Hours in Weekly View": "Часы в недельном обзоре",
    "Hours in Daily View": "Часы в ежедневном просмотре",
    "Start": "Начать",
    "End": "Конец",
    "At This Hour": "в этот час",
    "Add to": "Добавить в",
    "Button": "Кнопка",
    "Buttons": "Кнопки",
    "Sunday": "Воскресенье",
    "Monday": "Понедельник",
    "Tuesday": "Вторник",
    "Wednesday": "Среда",
    "Thursday": "Четверг",
    "Friday": "Пятница",
    "Saturday": "Суббота",
    "Default Date": "Дата по умолчанию",
    "year": "год",
    "month": "месяц",
    "days": "дней",
    "ago": "тому назад",
    "ahead": "впереди",
    "Yesterday": "Вчера",
    "Today": "Сегодня",
    "Tomorrow": "Завтра",
    "Custom": "Обычай",
    "Set Daily Rows Limit": "Установить дневной лимит строк",
    "Set Proportions": "Установите пропорции",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Разрешить посетителю добавлять события в локальные Calnedars: Google, Yahoo, Outlook, ICalendar.",
    "Container": "Контейнер",
    "Background": "Фон",
    "Container Background": "Фон Контейнерa",
    "Container Borders": "Контейнерные границы",
    "Calendar": "Календарь",
    "Event Info Tooltip": "Информация о событии",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "Когда люди наводят курсор на событие, они видят всю информацию о нем во всплывающей подсказке.",
    "Event Info Window": "Окно информации о событии",
    "This is the full information window that opens when someone clicks on the event.": "Это окно полной информации, которое открывается, когда кто-то нажимает на событие.",
    "Use Gradient": "Использовать градиент",
    "Vertical": "Вертикальный",
    "Horizontal": "Горизонтальный",
    "First": "Первый",
    "Second": "Второй",
    "diagonal": "Диагональ",
    "Radial": "Радиальный",
    "Select option": "Выберите опцию",
    "Solid": "Сплошной",
    "Dotted": "Пунктирный",
    "Dashed": "Пунктирная",
    "Double": "Двойной",
    "Border Radius": "Пограничный радиус",
    "Padding": "Ннабивка",
    "Date Header": "Заголовок даты",
    "Event Default Color": "Цвет события по умолчанию",
    "Days of Week": "Дни недели",
    "Days of Week Background": "Фон дней недель",
    "Date": "Дата",
    "Event Title": "Название мероприятия",
    "Highlight today": "Выделите сегодня",
    "Highlight Color": "Цвет подсветки",
    "Hide": "Спрятать",
    "Calendar Border Color": "Цвет границы календаря",
    "Calendar Border Width": "Ширина границы календаря",
    "Calendar Border Style": "Стиль Границы Календаря",
    "Font Color": "Цвет шрифта",
    "Event Background": "Фон события",
    "Card Date Color": "Цвет даты карты",
    "Title Font": "Название шрифта",
    "Date Font": "Дата Шрифта",
    "Description Font": "Описание шрифта",
    "Button Background": "Фон кнопки",
    "Button Text": "Текст кнопки",
    "Border Color": "Цвет границы",
    "Border Width": "Ширина рамки",
    "Border Type": "Тип границы",
    "Title": "Заглавие",
    "Description": "Описание",
    "Background Color": "Фоновый цвет",
    "Divider": "Делитель",
    "Event Details Font": "Событие Подробнее Шрифт",
    "Website Link Color": "Цвет Ссылки на Сайт",
    "Developer Info": "Информация про разработчиков",
    "User Guide": "Гид Пользователя",
    "Support e-mail": "Поддержка по e-mail",
    "Our Website": "Наш Сайт",
    "App Review": "Обзор приложения",
    "Enjoying App? Leave us a review in the App Market.": "Наслаждаешься приложением? Оставьте нам отзыв в App Market.",
    "Review Us": "Обзор",
    "Connect With Us": "Связаться с нами",
    "What's your email?": "Какой у тебя адрес электронной почты?",
    "Invalid email address!": "Неверный адрес электронной почты!",
    "Comments": "Комментарии",
    "We'd love to hear from you. Send us a message.": "Мы хотели бы услышать от вас. Отправьте нам сообщение.",
    "Message must be at least 5 characters long": "Сообщение должно быть не менее 5 символов",
    "Send": "Отправить",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Если вы хотите, чтобы пользователь мог переключаться между представлениями календаря, включите эту опцию и выберите представления, которые вы хотите показать.",
    "Main": "Главный",
    "Localize": "Локализировать",
    "Settings": "Настройки",
    "Layouts": "Макеты",
    "Advanced": "Продвинутый",
    "Design": "Дизайн",
    "Support": "Служба поддержки",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Все локальные настройки (автоматически) основаны на вашем языке. Если ваш язык есть в списке, нет необходимости настраивать этот раздел.",
    "Date Format":"Формат даты",
    "Time Format":"Формат времени",
    "Text Direction":"Направление текста",
    "Left to Right":"Слева направо",
    "Right to Left":"Справа налево",
    "Week Starts On":"Неделя начинается",
    "Agenda Style":"Стиль Повестки дня",
    "Classic":"Классический",
    "Modern":"Современный",
    "Agenda Header":"Повестка дня",
    "Upcoming Events":"Предстоящие События",
    "Agenda Event Limit":"Повестка дня мероприятия",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"Обновите сейчас и получите гораздо больше возможностей и наслаждайтесь вашим приложением в полном объеме!",
    "Upgrade Now":"Обнови сейчас",
    "Hosting events that last all day? This lets you show them on your calendar.":"Хостинг событий, которые длятся весь день? Это позволяет вам показывать их в своем календаре",
    "24 hours":"24 часа",
    "Sat": "Суб",
    "Sun": "Вос",
    "Mon": "Пон",
    "Default": "По умолчанию",
    "Select custom design style for your calendar.": "Выберите индивидуальный стиль дизайна для вашего календаря.",
    "Style": "Стиль",
    "Styles and Colors": "Стили и Цвета",
    "Calendar Name":"Название календаря",
    "Write your Calendar name here":"Напишите здесь название вашего календаря",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"Это не видно вашим пользователям. Задайте имена, чтобы дифференцировать календари при использовании функции синхронизации календаря Boom.",
    "General Info" : "Общая информация",
    "Venue" : "Место проведения",
    "Organizer"  : "Организатор"
};

export default ru;
