let sv = {
    "Language": "Språk",
    "Show Time Zone": "Visa tidszon",
    "Custom Local Settings": "Anpassade lokala inställningar",
    "Add and showcase events on your site using a beautiful calendar.": "Lägg till och visa upp händelser på din webbplats med en vacker kalender . ",
    "Week Days": "Veckodagar",
    "Manage Events": "Hantera händelser",
    "General": "Allmän",
    "Layout Picker": "Layoutväljare",
    "Month": "Månad",
    "Monthly": "En gång i månaden",
    "Week": "Vecka",
    "Weekly": "Varje vecka",
    "Day": "Dag",
    "Daily": "Dagligen",
    "Agenda": "Dagordning",
    "Navigation Buttons": "Navigeringsknappar",
    "Today": "I dag",
    "Week numbers": "Veckonummer",
    "Include Weekends": "Inkludera helger",
    "All-day": "Hela dagen",
    "All Day": "Hela dagen",
    "Label": "Märka",
    "Fit to Height": "Fit to Height",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "För att ställa in app-proportioner manuellt inaktivera detta alternativ och ändra storlek på kalender i Editor. ",
    "Default Layout": "Standard layout",
    "Monthly view": "Månadsvis",
    "Weekly and Daily view": "Veckovis och daglig vy",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Du kan ge besökarna en mer konsekvent upplevelse genom att visa samma antal veckor ( 6) åt gången.",
    "Fixed Weekly Layout": "Fast vecklayout",
    "back": " tillbaka ",
    "Row": "Rad",
    "Hours in Weekly View": "Öppettider i veckovisning",
    "Hours in Daily View": "Öppettider i daglig vy",
    "Start": "Start",
    "End": "Slutet",
    "At This Hour": "På denna timme",
    "Add to": "Lägg till",
    "Button": "Knapp",
    "Buttons": "Buttons",
    "Sunday": "Söndag",
    "Monday": "Måndag",
    "Tuesday": "Tisdag",
    "Wednesday": "Onsdag",
    "Thursday": " Torsdag ",
    "Friday": "Fredag",
    "Saturday": "Lördag",
    "Default Date": "Standard datum",
    "year": " år ",
    "month": " månad ",
    "days": " dagar ",
    "ago": " sedan ",
    "ahead": " framåt ",
    "Yesterday": "I går",
    "Today": "I dag",
    "Tomorrow": "I morgon",
    "Custom": "Beställnings",
    "Set Daily Rows Limit": "Ställ in dagliga rader gräns",
    "Set Proportions": "Ställ in proportioner",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Låt besökaren lägga till händelse i lokala kalendrar , Google, Yahoo, Outlook, ICalendar . ",
    "Container": "Behållare",
    "Background": "Bakgrund",
    "Container Background": "Behållarbakgrund",
    "Container Borders": "Container Borders",
    "Calendar": "Kalender",
    "Event Info Tooltip": "Verktygstips för händelsinfo",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "När människor svävar över en händelse ser de all information om det i ett verktygstips. ",
    "Event Info Window": "Event Info Window",
    "This is the full information window that opens when someone clicks on the event.": "Detta är det fullständiga informationsfönstret som öppnas när någon klickar på händelsen. ",
    "Use Gradient": "Använd lutning",
    "Vertical": "Vertikal",
    "Horizontal": "Horisontell",
    "First": "Först",
    "Second": "Andra",
    "diagonal": " diagonal ",
    "Radial": "Radiell",
    "Select option": "Välj alternativ",
    "Solid": "Fast",
    "Dotted": "Prickad",
    "Dashed": "Streckad",
    "Double": "Dubbel",
    "Border Radius": "Border Radius",
    "Padding": "Stoppning",
    "Date Header": "Datumrubrik",
    "Event Default Color": "Färg för standardhändelse",
    "Days of Week": "Veckodagar",
    "Days of Week Background": "Veckans bakgrund",
    "Date": "Datum",
    "Event Title": "Händelsetitel",
    "Highlight today": "Markera idag",
    "Highlight Color": "Markeringsfärg",
    "Hide": "Dölj",
    "Calendar Border Color": "Kalendergränsfärg",
    "Calendar Border Width": "Kalendergränsbredd",
    "Calendar Border Style": "Kalendergränsstil",
    "Font Color": "Fontfärg",
    "Event Background": "Händelsebakgrund",
    "Card Date Color": "Kortdatafärg",
    "Title Font": "Titelteckensnitt",
    "Date Font": "Date Font",
    "Description Font": "Beskrivningsteckensnitt",
    "Button Background": "Knappbakgrund",
    "Button Text": "Knapp-text",
    "Border Color": "Gräns ​​färg",
    "Border Width": "Gränsbredd",
    "Border Type": "Border Type",
    "Title": "Titel",
    "Description": "Beskrivning",
    "Background Color": "Bakgrundsfärg",
    "Divider": "Delare",
    "Event Details Font": "Teckensnitt för händelsedetaljer",
    "Website Link Color": "Färg på webbplatslänk",
    "Developer Info": "Utvecklarinfo",
    "User Guide": "Användarguide",
    "Support e-mail": "Stöd e-post",
    "Our Website": "Vår websida",
    "App Review": "Appgranskning",
    "Enjoying App? Leave us a review in the App Market.": "Att njuta av appen? Lämna oss en recension på appmarknaden. ",
    "Review Us": "Granska oss",
    "Connect With Us": "Anslut oss",
    "What's your email?": "Vad är din e-post? ",
    "Invalid email address!": "Ogiltig e-postadress! ",
    "Comments": "Kommentarer",
    "We'd love to hear from you. Send us a message.": "Vi vill gärna höra från dig. Skicka ett meddelande. ",
    "Message must be at least 5 characters long": "Meddelandet måste vara minst fem tecken långt",
    "Send": "Skicka",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Om du vill tillåta användare att växla mellan kalendervyer aktiverar du det här alternativet och väljer vyerna du vill visa. ",
    "Main": "Huvudsaklig",
    "Localize": "Lokalisera",
    "Settings": "Inställningar",
    "Layouts": "Layouter",
    "Advanced": "Avancerad",
    "Design": "Design",
    "Support": "Stöd",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Alla lokala inställningar är (automatiskt) baserade på ditt språk. Om ditt språk finns på listan behöver du inte anpassa det här avsnittet.",
    "Date Format":"Datumformat",
    "Time Format":"Tidsformat",
    "Text Direction":"Textriktning",
    "Left to Right":"Vänster till höger",
    "Right to Left":"Höger till vänster",
    "Week Starts On":"Veckan börjar",
    "Agenda Style":"Agenda Style",
    "Classic":"Klassisk",
    "Modern":"Modern",
    "Agenda Header":"Agenda-rubrik",
    "Upcoming Events":"Uppkommande händelser",
    "Agenda Event Limit":"Agenda Event Limit",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"Uppgradera nu och få mycket fler funktioner och njut av din APP i sin helhet!",
    "Upgrade Now":"Uppgradera nu",
    "Hosting events that last all day? This lets you show them on your calendar.":"Värdar händelser som pågår hela dagen? Detta låter dig visa dem i din kalender.",
    "24 hours":"24 timmar",
    "Sun": "Sön",
    "Mon": "Mån",
    "Sat": "Lör",
    "Default": "Standard",
    "Select custom design style for your calendar.": "Välj anpassad designstil för din kalender.",
    "Style": "Stil",
    "Styles and Colors": "Stilar och färger",
    "Calendar Name":"Kalendernamn",
    "Write your Calendar name here":"Skriv ditt kalendernamn här",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"Detta är inte synligt för dina användare. Ställ in namn för att skilja dina kalendrar när du använder funktionen Boom Calendar Sync.",
    "General Info" : "Generell information",
    "Venue" : "Mötesplats",
    "Organizer"  : "Arrangör"

};

export default sv;
