let th = {
    "Language": "ภาษา",
    "Show Time Zone": "แสดงเขตเวลา",
    "Custom Local Settings": "การตั้งค่าท้องถิ่นที่กำหนดเอง",
    "Add and showcase events on your site using a beautiful calendar.": "เพิ่มและแสดงเหตุการณ์ที่เกิดขึ้นในเว็บไซต์ของคุณโดยใช้ปฏิทินที่สวยงาม. ",
    "Week Days": "วันในสัปดาห์",
    "Manage Events": "จัดการกิจกรรม",
    "General": "ทั่วไป",
    "Layout Picker": "เครื่องมือเลือกเค้าโครง",
    "Month": "เดือน",
    "Monthly": "รายเดือน",
    "Week": "สัปดาห์",
    "Weekly": "รายสัปดาห์",
    "Day": "วัน",
    "Daily": "รายวัน",
    "Agenda": "วาระ",
    "Navigation Buttons": "ปุ่มนำทาง",
    "Today": "วันนี้",
    "Week numbers": "หมายเลขสัปดาห์",
    "Include Weekends": "รวมวันหยุดสุดสัปดาห์",
    "All-day": "ทั้งวัน",
    "All Day": "ทั้งวัน",
    "Label": "ฉลาก",
    "Fit to Height": "พอดีกับความสูง",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "ในการตั้งค่าสัดส่วนแอพmanully ปิดการใช้งานตัวเลือกนี้และปรับขนาดปฏิทินในเครื่องมือแก้ไข",
    "Default Layout": "เค้าโครงเริ่มต้น",
    "Monthly view": "มุมมองรายเดือน",
    "Weekly and Daily view": "มุมมองรายสัปดาห์และรายวัน",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "คุณสามารถมอบประสบการณ์ที่สอดคล้องกันมากขึ้นให้กับผู้เข้าชมด้วยการแสดงจำนวนสัปดาห์ ( 6) ต่อครั้ง",
    "Fixed Weekly Layout": "แก้ไขเค้าโครงประจำสัปดาห์",
    "back": " ย้อนกลับ",
    "Row": "แถว",
    "Hours in Weekly View": "ชั่วโมงในการดูแบบรายสัปดาห์",
    "Hours in Daily View": "ชั่วโมงในการดูรายวัน",
    "Start": "เริ่มต้น",
    "End": "End",
    "At This Hour": "ในเวลานี้",
    "Add to": "เพิ่ม",
    "Button": "ปุ่ม",
    "Buttons": "ปุ่ม",
    "Sunday": "อาทิตย์",
    "Monday": "จันทร์",
    "Tuesday": "อังคาร",
    "Wednesday": "พุธ",
    "Thursday": " วันพฤหัสบดี",
    "Friday": "ศุกร์",
    "Saturday": "วันเสาร์",
    "Default Date": "วันที่เริ่มต้น",
    "year": " ปี",
    "month": " เดือน",
    "days": " วัน",
    "ago": " ที่ผ่านมา",
    "ahead": " ไปข้างหน้า",
    "Yesterday": "เมื่อวานนี้",
    "Today": "วันนี้",
    "Tomorrow": "วันพรุ่งนี้",
    "Custom": "กำหนดเอง",
    "Set Daily Rows Limit": "ตั้งค่า จำกัด จำนวนแถวต่อวัน",
    "Set Proportions": "ตั้งสัดส่วน",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "อนุญาตให้ผู้เข้าชมเพื่อเพิ่มกิจกรรมท้องถิ่นCalnedars , Google, Yahoo, Outlook, iCalendar . ",
    "Container": "ตู้คอนเทนเนอร์",
    "Background": "พื้นหลัง",
    "Container Background": "พื้นหลังคอนเทนเนอร์",
    "Container Borders": "เส้นขอบคอนเทนเนอร์",
    "Calendar": "ปฏิทิน",
    "Event Info Tooltip": "คำแนะนำเครื่องมือข้อมูลกิจกรรม",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "เมื่อผู้คนเลื่อนเมาส์ไปที่เหตุการณ์พวกเขาจะเห็นข้อมูลทั้งหมดเกี่ยวกับเหตุการณ์ในคำแนะนำเครื่องมือ",
    "Event Info Window": "หน้าต่างข้อมูลกิจกรรม",
    "This is the full information window that opens when someone clicks on the event.": "นี่เป็นหน้าต่างข้อมูลเต็มรูปแบบที่เปิดขึ้นเมื่อมีคนคลิกที่เหตุการณ์",
    "Use Gradient": "ใช้การไล่ระดับสี",
    "Vertical": "แนวตั้ง",
    "Horizontal": "แนวนอน",
    "First": "ครั้งแรก",
    "Second": "สอง",
    "diagonal": " แนวทแยง",
    "Radial": "รัศมี",
    "Select option": "เลือกตัวเลือก",
    "Solid": "ของแข็ง",
    "Dotted": "ประ",
    "Dashed": "ประ",
    "Double": "ดับเบิล",
    "Border Radius": "รัศมีชายแดน",
    "Padding": "การขยายความ",
    "Date Header": "ส่วนหัววันที่",
    "Event Default Color": "สีเริ่มต้นของเหตุการณ์",
    "Days of Week": "วันในสัปดาห์",
    "Days of Week Background": "พื้นหลังของวันในสัปดาห์",
    "Date": "วัน",
    "Event Title": "ชื่อกิจกรรม",
    "Highlight today": "ไฮไลต์วันนี้",
    "Highlight Color": "เน้นสี",
    "Hide": "ซ่อน",
    "Calendar Border Color": "สีเส้นขอบปฏิทิน",
    "Calendar Border Width": "ความกว้างชายแดนปฏิทิน",
    "Calendar Border Style": "สไตล์เส้นขอบปฏิทิน",
    "Font Color": "สีตัวอักษร",
    "Event Background": "พื้นหลังของเหตุการณ์",
    "Card Date Color": "สีของวันที่บัตร",
    "Title Font": "แบบอักษรของชื่อ",
    "Date Font": "วันที่อักษร",
    "Description Font": "คำอธิบายตัวอักษร",
    "Button Background": "พื้นหลังปุ่ม",
    "Button Text": "ข้อความปุ่ม",
    "Border Color": "สีเส้นขอบ",
    "Border Width": "ความกว้างชายแดน",
    "Border Type": "ประเภทชายแดน",
    "Title": "หัวข้อ",
    "Description": "คำอธิบาย",
    "Background Color": "สีพื้นหลัง",
    "Divider": "ตัวคั่น",
    "Event Details Font": "แบบอักษรรายละเอียดกิจกรรม",
    "Website Link Color": "สีลิงค์เว็บไซต์",
    "Developer Info": "ข้อมูลผู้พัฒนา",
    "User Guide": "คู่มือผู้ใช้",
    "Support e-mail": "รองรับอีเมล",
    "Our Website": "เว็บไซต์ของเรา",
    "App Review": "รีวิวแอพ",
    "Enjoying App? Leave us a review in the App Market.": "เพลิดเพลินกับแอพหรือยังปล่อยให้เรารีวิวใน App Market ",
    "Review Us": "ตรวจสอบเรา",
    "Connect With Us": "เชื่อมต่อกับเรา",
    "What's your email?": "อีเมลของคุณคืออะไร",
    "Invalid email address!": "ที่อยู่อีเมลไม่ถูกต้อง! ",
    "Comments": "ความคิดเห็น",
    "We'd love to hear from you. Send us a message.": "เราชอบที่จะได้ยินจากคุณส่งข้อความถึงเรา",
    "Message must be at least 5 characters long": "ข้อความต้องมีความยาวอย่างน้อย 5 ตัวอักษร",
    "Send": "ส่ง",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "หากคุณต้องการอนุญาตให้ผู้ใช้สลับระหว่างมุมมองปฏิทินให้เปิดใช้งานตัวเลือกนี้และเลือกมุมมองที่คุณต้องการแสดง",
    "Main": "หลัก",
    "Localize": "จำกัด",
    "Settings": "การตั้งค่า",
    "Layouts": "เลย์เอาต์",
    "Advanced": "สูง",
    "Design": "ออกแบบ",
    "Support": "สนับสนุน",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "การตั้งค่าท้องถิ่นทั้งหมด (โดยอัตโนมัติ) ตามภาษาของคุณ หากภาษาของคุณอยู่ในรายการคุณไม่จำเป็นต้องกำหนดหัวข้อนี้เอง",
    "Date Format":"รูปแบบวันที่",
    "Time Format":"รูปแบบเวลา",
    "Text Direction":"ทิศทางข้อความ",
    "Left to Right":"จากซ้ายไปขวา",
    "Right to Left":"จากขวาไปซ้าย",
    "Week Starts On":"สัปดาห์เริ่มต้นใน",
    "Agenda Style":"สไตล์กำหนดการ",
    "Classic":"คลาสสิก",
    "Modern":"ทันสมัย",
    "Agenda Header":"ส่วนหัวของวาระ",
    "Upcoming Events":"เหตุการณ์ที่จะเกิดขึ้น",
    "Agenda Event Limit":"ขีด จำกัด เหตุการณ์วาระ",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"อัปเกรดทันทีและรับคุณสมบัติเพิ่มเติมมากมายและสนุกกับแอพของคุณแบบเต็ม!",
    "Upgrade Now":"อัพเกรดเดี๋ยวนี้",
    "Hosting events that last all day? This lets you show them on your calendar.":"การโฮสต์กิจกรรมที่ยาวนานตลอดทั้งวันจะให้คุณแสดงในปฏิทินของคุณ",
    "24 hours":"24 ชั่วโมง",
    "Sat": "วันเสาร์",
    "Sun": "อาทิตย์",
    "Mon": "จันทร์",
    "Default": "ค่าเริ่มต้น",
    "Select custom design style for your calendar.": "เลือกสไตล์การออกแบบที่กำหนดเองสำหรับปฏิทินของคุณ",
    "Style": "สไตล์",
    "Styles and Colors": "สไตล์และสี",
    "Calendar Name":"ชื่อปฏิทิน",
    "Write your Calendar name here":"เขียนชื่อปฏิทินของคุณที่นี่",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"ผู้ใช้ของคุณจะไม่เห็นสิ่งนี้ ตั้งชื่อเพื่อแยกความแตกต่างปฏิทินของคุณเมื่อใช้ฟังก์ชัน Boom Calendar Sync",
    "General Info" : "ข้อมูลทั่วไป",
    "Venue" : "แห่ง",
    "Organizer"  : "ออแกไนเซอร์"

};

export default th;
