let tr = {
    "Language": "Dil",
    "Show Time Zone": "Saat Dilimini Göster",
    "Custom Local Settings": "Özel Yerel Ayarlar",
    "Add and showcase events on your site using a beautiful calendar.": "Güzel bir takvim kullanarak sitenize etkinlik ekleyin ve sergileyin . ",
    "Week Days": "Hafta içi",
    "Manage Events": "Etkinlikleri Yönet",
    "General": "Genel",
    "Layout Picker": "Düzen Seçici",
    "Month": "Ay",
    "Monthly": "Aylık",
    "Week": "Hafta",
    "Weekly": "Haftalık",
    "Day": "Gün",
    "Daily": "Günlük",
    "Agenda": "Gündem",
    "Navigation Buttons": "Yön tuşları",
    "Today": "Bugün",
    "Week numbers": "Hafta numaraları",
    "Include Weekends": "Hafta Sonlarını Dahil Et",
    "All-day": "Tüm gün",
    "All Day": "Tüm gün",
    "Label": "Etiket",
    "Fit to Height": "Yüksekliğe Sığdır",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "Uygulama oranlarını ayarlamak için bu seçeneği manüel olarak devre dışı bırakın ve Takvimi Editör'de Yeniden Boyutlandırın. ",
    "Default Layout": "Varsayılan Düzen",
    "Monthly view": "Aylık görünüm",
    "Weekly and Daily view": "Haftalık ve Günlük görünüm",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": " Bir kerede aynı haftaları ( 6) göstererek ziyaretçilere daha tutarlı bir deneyim sunabilirsiniz .",
    "Fixed Weekly Layout": "Sabit Haftalık Düzen",
    "back": " geri ",
    "Row": "Kürek çekmek",
    "Hours in Weekly View": "Haftalık Görünümde Saatler",
    "Hours in Daily View": "Günlük Görünümde Saatler",
    "Start": "Başla",
    "End": "Son",
    "At This Hour": "Bu saatte",
    "Add to": "A ekle",
    "Button": "Buton",
    "Buttons": "Düğmeler",
    "Sunday": "Pazar",
    "Monday": "Pazartesi",
    "Tuesday": "Salı",
    "Wednesday": "Çarşamba",
    "Thursday": " Perşembe ",
    "Friday": "Cuma",
    "Saturday": "Cumartesi",
    "Default Date": "Varsayılan Tarih",
    "year": " yıl ",
    "month": " ay ",
    "days": " günler ",
    "ago": " önce ",
    "ahead": " ileri ",
    "Yesterday": "Dün",
    "Today": "Bugün",
    "Tomorrow": "Yarın",
    "Custom": "Görenek",
    "Set Daily Rows Limit": "Günlük Satır Sınırını Ayarla",
    "Set Proportions": "Oranları Ayarla",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Ziyaretçilerin yerel Calnedar'lara etkinlik eklemesine izin ver , Google, Yahoo, Outlook, ICalendar . ",
    "Container": "Konteyner",
    "Background": "Arka fon",
    "Container Background": "Konteyner Arka Planı",
    "Container Borders": "Konteyner Sınırları",
    "Calendar": "Takvim",
    "Event Info Tooltip": "Etkinlik Bilgisi İpucu",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "İnsanlar bir etkinliğin üzerine geldiğinde, onunla ilgili tüm bilgileri bir araç ipucunda görürler. ",
    "Event Info Window": "Etkinlik Bilgi Penceresi",
    "This is the full information window that opens when someone clicks on the event.": "Bu, bir kişi etkinliği tıklattığında açılan tüm bilgi penceresidir. ",
    "Use Gradient": "Gradyanı Kullan",
    "Vertical": "Dikey",
    "Horizontal": "Yatay",
    "First": "İlk",
    "Second": "İkinci",
    "diagonal": " diyagonal ",
    "Radial": "Radyal",
    "Select option": "Seçeneği seç",
    "Solid": "Katı",
    "Dotted": "Noktalı",
    "Dashed": "Kesik",
    "Double": "Çift",
    "Border Radius": "Sınır Yarıçapı",
    "Padding": "Dolgu malzemesi",
    "Date Header": "Tarih Başlığı",
    "Event Default Color": "Etkinlik Varsayılan Rengi",
    "Days of Week": "Haftanın günleri",
    "Days of Week Background": "Haftanın Günleri Arkaplan",
    "Date": "Tarih",
    "Event Title": "Olay başlığı",
    "Highlight today": "Bugün vurgula",
    "Highlight Color": "Vurgu Rengi",
    "Hide": "Saklamak",
    "Calendar Border Color": "Takvim Kenarlığı Rengi",
    "Calendar Border Width": "Takvim Sınır Genişliği",
    "Calendar Border Style": "Takvim Sınır Stili",
    "Font Color": "Yazı rengi",
    "Event Background": "Etkinlik Arka Planı",
    "Card Date Color": "Kart Tarihi Rengi",
    "Title Font": "Başlık Yazı Tipi",
    "Date Font": "Tarih Yazı Tipi",
    "Description Font": "Açıklama Yazı Tipi",
    "Button Background": "Düğme Arka Planı",
    "Button Text": "Düğme Metni",
    "Border Color": "Sınır rengi",
    "Border Width": "Sınır Genişliği",
    "Border Type": "Sınır Türü",
    "Title": "Başlık",
    "Description": "Açıklama",
    "Background Color": "Arka plan rengi",
    "Divider": "Bölücü",
    "Event Details Font": "Etkinlik Ayrıntıları Yazı Tipi",
    "Website Link Color": "Web Sitesi Bağlantı Rengi",
    "Developer Info": "Geliştirici Bilgisi",
    "User Guide": "Kullanici rehberi",
    "Support e-mail": "Destek e-postası",
    "Our Website": "Web Sitemiz",
    "App Review": "Uygulama İncelemesi",
    "Enjoying App? Leave us a review in the App Market.": "App Eğleniyor? Bize App Market hakkında bir inceleme bırakın . ",
    "Review Us": "Bizi İnceleyin",
    "Connect With Us": "Bizimle iletişime geçin",
    "What's your email?": "E-posta adresin nedir? ",
    "Invalid email address!": "Geçersiz e-posta adresi! ",
    "Comments": "Yorumlar",
    "We'd love to hear from you. Send us a message.": "Sizden haber almak isteriz.Bize bir mesaj gönderin.",
    "Message must be at least 5 characters long": "Mesaj en az 5 karakter uzunluğunda olmalı",
    "Send": "Gönder",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Kullanıcının takvim görünümleri arasında geçiş yapmasına izin vermek istiyorsanız, bu seçeneği etkinleştirin ve göstermek istediğiniz görünümleri seçin. ",
    "Main": "Ana",
    "Localize": "Yerelleştirmek",
    "Settings": "Ayarlar",
    "Layouts": "Düzenleri",
    "Advanced": "Ileri",
    "Design": "Dizayn",
    "Support": "Destek",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Tüm yerel ayarlar dilinize göre (otomatik olarak) yapılır. Diliniz listede ise, bu bölümü özelleştirmenize gerek yoktur.",
    "Date Format":"Tarih formatı",
    "Time Format":"Zaman formatı",
    "Text Direction":"Metin yönü",
    "Left to Right":"Soldan sağa",
    "Right to Left":"Sağdan sola",
    "Week Starts On":"Hafta Başlıyor",
    "Agenda Style":"Gündem Stili",
    "Classic":"Klasik",
    "Modern":"Modern",
    "Agenda Header":"Gündem Başlığı",
    "Upcoming Events":"Yaklaşan Etkinlikler",
    "Agenda Event Limit":"Gündem Etkinlik Sınırı",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"Şimdi yükseltin ve daha fazla özellik edinin ve uygulamanızın keyfini tam olarak çıkarın!",
    "Upgrade Now":"Şimdi Yükselt",
    "Hosting events that last all day? This lets you show them on your calendar.":"Bütün gün süren etkinlikleri barındırmak mı? Bu, takviminizde onlara göstermenizi sağlar.",
    "24 hours":"24 saat",
    "Sun": "Pazar",
    "Mon": "Pazartesi",
    "Sat": "Cumartesi",
    "Default": "Varsayılan",
    "Select custom design style for your calendar.": "Takviminiz için özel tasarım stilini seçin.",
    "Style": "Stil",
    "Styles and Colors": "Stiller ve Renkler",
    "Calendar Name":"Takvim Adı",
    "Write your Calendar name here":"Takvim adınızı buraya yazın",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"Bu, kullanıcılarınız tarafından görülemez. Boom Calendar Sync işlevini kullanırken takvimlerinizi ayırt etmek için adları ayarlayın.",
    "General Info" : "Genel Bilgi",
    "Venue" : "Mekan",
    "Organizer"  : "Organizatör"
};

export default tr;
