let uk = {
    "Language": "Мова",
    "Show Time Zone": "Показати часовий пояс",
    "Custom Local Settings": "Спеціальні локальні налаштування",
    "Add and showcase events on your site using a beautiful calendar.": "Додайте та демонструйте події на своєму сайті за допомогою прекрасного календаря . ",
    "Week Days": "Дні тижня",
    "Manage Events": "Керуйте подіями",
    "General": "Загальні",
    "Layout Picker": "Вибір макета",
    "Month": "Місяць",
    "Monthly": "Щомісяця",
    "Week": "Тиждень",
    "Weekly": "Щотижня",
    "Day": "День",
    "Daily": "Щодня",
    "Agenda": "Порядок денний",
    "Navigation Buttons": "Кнопки навігації",
    "Today": "Сьогодні",
    "Week numbers": "Номери тижнів",
    "Include Weekends": "Включити вихідні дні",
    "All-day": "Весь день",
    "All Day": "Весь день",
    "Label": "Мітка",
    "Fit to Height": "Підходить до висоти",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "Щоб встановити пропорції програми, ручним чином відключіть цю опцію та змініть розмір календаря в редакторі. ",
    "Default Layout": "Макет за замовчуванням",
    "Monthly view": "Щомісячний перегляд",
    "Weekly and Daily view": "Щотижневий і щоденний перегляд",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Ви можете надати відвідувачам більш послідовний досвід, показуючи однакову кількість тижнів ( 6) за один раз.",
    "Fixed Weekly Layout": "Фіксований тижневий макет",
    "back": " назад ",
    "Row": "Рядок",
    "Hours in Weekly View": "Години в тижневому перегляді",
    "Hours in Daily View": "Години в щоденному перегляді",
    "Start": "Почати",
    "End": "Кінець",
    "At This Hour": "У цю годину",
    "Add to": "Додати до",
    "Button": "Кнопка",
    "Buttons": "Кнопки",
    "Sunday": "Неділя",
    "Monday": "Понеділок",
    "Tuesday": "Вівторок",
    "Wednesday": "Середа",
    "Thursday": " Четвер ",
    "Friday": "П'ятниця",
    "Saturday": "Субота",
    "Default Date": "Дата за замовчуванням",
    "year": " рік ",
    "month": " місяць ",
    "days": " днів ",
    "ago": " тому ",
    "ahead": " вперед ",
    "Yesterday": "Вчора",
    "Today": "Сьогодні",
    "Tomorrow": "Завтра",
    "Custom": "Спеціальні",
    "Set Daily Rows Limit": "Встановити обмеження щоденних рядків",
    "Set Proportions": "Встановити пропорції",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Дозволити відвідувачу додавати подію до місцевих Calnedars , Google, Yahoo, Outlook, ICalendar . ",
    "Container": "Контейнер",
    "Background": "Фон",
    "Container Background": "Фон контейнера",
    "Container Borders": "Межі контейнерів",
    "Calendar": "Календар",
    "Event Info Tooltip": "Підказка про інформацію про подію",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "Коли люди наведіть курсор на подію, вони побачать всю інформацію про неї в підказці. ",
    "Event Info Window": "Вікно інформації про подію",
    "This is the full information window that opens when someone clicks on the event.": "Це повне інформаційне вікно, яке відкриється, коли хтось натискає на подію. ",
    "Use Gradient": "Використовувати градієнт",
    "Vertical": "Вертикальна",
    "Horizontal": "Горизонтальний",
    "First": "Спочатку",
    "Second": "Друге",
    "diagonal": " діагональ ",
    "Radial": "Радіальні",
    "Select option": "Вибрати варіант",
    "Solid": "Суцільний",
    "Dotted": "Пунктирними",
    "Dashed": "Збито",
    "Double": "Подвійний",
    "Border Radius": "Прикордонний радіус",
    "Padding": "Набивання",
    "Date Header": "Заголовок дати",
    "Event Default Color": "Колір події за замовчуванням",
    "Days of Week": "Дні тижня",
    "Days of Week Background": "Фон днів тижня",
    "Date": "Дата",
    "Event Title": "Назва події",
    "Highlight today": "Виділіть сьогодні",
    "Highlight Color": "Колір виділення",
    "Hide": "Сховати",
    "Calendar Border Color": "Колір рамки календаря",
    "Calendar Border Width": "Ширина межі календаря",
    "Calendar Border Style": "Стиль межі календаря",
    "Font Color": "Колір шрифту",
    "Event Background": "Фон події",
    "Card Date Color": "Колір дати картки",
    "Title Font": "Шрифт заголовка",
    "Date Font": "Шрифт дати",
    "Description Font": "Опис шрифту",
    "Button Background": "Фон кнопки",
    "Button Text": "Текст кнопки",
    "Border Color": "Колір межі",
    "Border Width": "Ширина кордону",
    "Border Type": "Тип кордону",
    "Title": "Назва",
    "Description": "Опис",
    "Background Color": "Колір фону",
    "Divider": "Дільник",
    "Event Details Font": "Шрифт деталей події",
    "Website Link Color": "Колір посилання на веб-сайт",
    "Developer Info": "Інформація для розробника",
    "User Guide": "Керівництво користувача",
    "Support e-mail": "Підтримка електронної пошти",
    "Our Website": "Наш веб-сайт",
    "App Review": "Огляд додатків",
    "Enjoying App? Leave us a review in the App Market.": "Насолоджується додатком? Залиште нам відгук на ринку додатків. ",
    "Review Us": "Перегляньте нас",
    "Connect With Us": "Зв'яжіться з нами",
    "What's your email?": "Який ваш електронний лист? ",
    "Invalid email address!": "Недійсна адреса електронної пошти! ",
    "Comments": "Коментарі",
    "We'd love to hear from you. Send us a message.": "Ми хотіли б почутись від вас. Надішліть нам повідомлення. ",
    "Message must be at least 5 characters long": "Повідомлення має бути не менше 5 символів",
    "Send": "Надіслати",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Якщо ви хочете дозволити користувачу перемикатися між переглядами календаря, увімкніть цю опцію та виберіть представлення, яке ви хочете показати. ",
    "Main": "Основна",
    "Localize": "Локалізувати",
    "Settings": "Налаштування",
    "Layouts": "Макети",
    "Advanced": "Розширений",
    "Design": "Дизайн",
    "Support": "Підтримка",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Усі локальні налаштування (автоматично) базуються на вашій мові. Якщо ваша мова є у списку, не потрібно налаштовувати цей розділ.",
    "Date Format":"Формат дати",
    "Time Format":"Формат часу",
    "Text Direction":"Напрямок тексту",
    "Left to Right":"Зліва направо",
    "Right to Left":"Право наліво",
    "Week Starts On":"Починається тиждень",
    "Agenda Style":"Стиль порядку денного",
    "Classic":"Класичний",
    "Modern":"Сучасний",
    "Agenda Header":"Заголовок порядку денного",
    "Upcoming Events":"Майбутні події",
    "Agenda Event Limit":"Обмеження події порядку денного",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"Оновіть зараз і отримайте набагато більше функцій та насолоджуйтесь своїм додатком повністю!",
    "Upgrade Now":"Оновити зараз",
    "Hosting events that last all day? This lets you show them on your calendar.":"Хостинг подій, які тривають цілий день? Це дозволяє показувати їх у своєму календарі.",
    "24 hours":"24 години",
    "Sat": "Суб",
    "Sun": "Нед",
    "Mon": "Пон",
    "Default": "За замовчуванням",
    "Select custom design style for your calendar.": "Виберіть власний стиль дизайну для вашого календаря.",
    "Style":"Стиль",
    "Styles and Colors": "Стилі та кольори",
    "Calendar Name":"Назва календаря",
    "Write your Calendar name here":"Напишіть тут своє ім’я календаря",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"Це не видно користувачам. Встановіть імена для розмежування ваших календарів під час використання функції синхронізації календаря Boom.",
    "General Info" : "Загальна інформація",
    "Venue" : "Місце проведення",
    "Organizer"  : "Організатор"

};

export default uk;
