let zh = {
    "Language": "语言",
    "Show Time Zone": "显示时区",
    "Custom Local Settings": "自定义本地设置",
    "Add and showcase events on your site using a beautiful calendar.": "使用漂亮的日历在您的网站上添加和展示活动。",
    "Week Days": "周日",
    "Manage Events": "管理活动",
    "General": "一般",
    "Layout Picker": "布局选择器",
    "Month": "月",
    "Monthly": "每月",
    "Week": "周",
    "Weekly": "每周",
    "Day": "天",
    "Daily": "日常",
    "Agenda": "议程",
    "Navigation Buttons": "导航按钮",
    "Today": "今天",
    "Week numbers": "周数",
    "Include Weekends": "包括周末",
    "All-day": "一整天",
    "All Day": "一整天",
    "Label": "标签",
    "Fit to Height": "适合身高",
    "To set App proportions manully disable this option and resize Calendar in Editor.": "要设置应用程序比例，请手动禁用此选项并在编辑器中调整日历大小。",
    "Default Layout": "默认布局",
    "Monthly view": "每月观点",
    "Weekly and Daily view": "每周和每日观点",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "通过一次显示相同的周数（6），您可以为访问者提供更一致的体验。",
    "Fixed Weekly Layout": "固定每周布局",
    "back": " 回",
    "Row": "行",
    "Hours in Weekly View": "每周视图中的小时数",
    "Hours in Daily View": "每日观看时间",
    "Start": "开始",
    "End": "结束",
    "At This Hour": "在这个时刻",
    "Add to": "添加",
    "Button": "按钮",
    "Buttons": "纽扣",
    "Sunday": "星期日",
    "Monday": "星期一",
    "Tuesday": "星期二",
    "Wednesday": "星期三",
    "Thursday": " 星期四",
    "Friday": "星期五",
    "Saturday": "星期六",
    "Default Date": "默认日期",
    "year": " 年",
    "month": " 月",
    "days": " 天",
    "ago": " 以前",
    "ahead": " 领先",
    "Yesterday": "昨天",
    "Today": "今天",
    "Tomorrow": "明天",
    "Custom": "自定义",
    "Set Daily Rows Limit": "设置每日行限制",
    "Set Proportions": "设置比例",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "允许访问者向当地的Calnedars 添加活动,Google，Yahoo，Outlook，ICalendar 。",
    "Container": "容器",
    "Background": "背景",
    "Container Background": "容器背景",
    "Container Borders": "集装箱边界",
    "Calendar": "日历",
    "Event Info Tooltip": "活动信息工具提示",
    "When people hover over an event they’ll see all the info about it in a tooltip.": "当人们在事件上盘旋时，他们会在工具提示中看到有关它的所有信息。",
    "Event Info Window": "活动信息窗口",
    "This is the full information window that opens when someone clicks on the event.": "这是当有人点击事件时打开的完整信息窗口。",
    "Use Gradient": "使用渐变",
    "Vertical": "垂直",
    "Horizontal": "水平",
    "First": "第一",
    "Second": "第二",
    "diagonal": " 对角线",
    "Radial": "子午线",
    "Select option": "选择选项",
    "Solid": "固体",
    "Dotted": "虚线",
    "Dashed": "虚线",
    "Double": "双",
    "Border Radius": "边界半径",
    "Padding": "填充",
    "Date Header": "日期标题",
    "Event Default Color": "事件默认颜色",
    "Days of Week": "星期几",
    "Days of Week Background": "周日背景",
    "Date": "日期",
    "Event Title": "活动标题",
    "Highlight today": "今日亮点",
    "Highlight Color": "突出显示颜色",
    "Hide": "隐藏",
    "Calendar Border Color": "日历边框颜色",
    "Calendar Border Width": "日历边框宽度",
    "Calendar Border Style": "日历边框样式",
    "Font Color": "字体颜色",
    "Event Background": "活动背景",
    "Card Date Color": "卡片日期颜色",
    "Title Font": "标题字体",
    "Date Font": "日期字体",
    "Description Font": "描述字体",
    "Button Background": "按钮背景",
    "Button Text": "按钮文字",
    "Border Color": "边框颜色",
    "Border Width": "边界宽度",
    "Border Type": "边境类型",
    "Title": "标题",
    "Description": "描述",
    "Background Color": "背景颜色",
    "Divider": "除法",
    "Event Details Font": "活动详情字体",
    "Website Link Color": "网站链接颜色",
    "Developer Info": "开发者信息",
    "User Guide": "用户指南",
    "Support e-mail": "支持电子邮件",
    "Our Website": "我们的网站",
    "App Review": "App Review",
    "Enjoying App? Leave us a review in the App Market.": "享受App？在App Market 留下评论。",
    "Review Us": "回顾我们",
    "Connect With Us": "联系我们",
    "What's your email?": "你的电子邮件是什么？",
    "Invalid email address!": "电子邮件地址无效！",
    "Comments": "评论",
    "We'd love to hear from you. Send us a message.": "我们很乐意听取您的意见。给我们留言。",
    "Message must be at least 5 characters long": "邮件长度必须至少为5个字符",
    "Send": "发送",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "如果您想允许用户在日历视图之间切换，请启用此选项并选择您要显示的视图。",
    "Main": "主要",
    "Localize": "本土化",
    "Settings": "设置",
    "Layouts": "布局",
    "Advanced": "高级",
    "Design": "设计",
    "Support": "支持",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "所有本地设置都是（自动）基于您的语言。 如果您的语言在列表中，则无需自定义此部分。",
    "Date Format":"日期格式",
    "Time Format":"时间格式",
    "Text Direction":"文字方向",
    "Left to Right":"左到右",
    "Right to Left":"右到左",
    "Week Starts On":"周开始",
    "Agenda Style":"议程风格",
    "Classic":"经典",
    "Modern":"现代",
    "Agenda Header":"议程标题",
    "Upcoming Events":"接下来的活动",
    "Agenda Event Limit":"议程事件限制",
    "Upgrade now and get a lot more features and enjoy your APP in full!":"立即升级，获得更多功能，全面享受您的APP！",
    "Upgrade Now":"现在升级",
    "Hosting events that last all day? This lets you show them on your calendar.":"主持持续一整天的活动？这可以让你在日历上显示它们。",
    "24 hours":"24小时",
    "Sun": "星期日",
    "Mon": "星期一",
    "Sat": "星期六",
    "Default": "默认",
    "Select custom design style for your calendar.": "为您的日历选择自定义设计风格。",
    "Style": "样式",
    "Styles and Colors": "款式和顏色",
    "Calendar Name":"日曆名稱",
    "Write your Calendar name here":"在這裡寫下您的日曆名稱",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"這對您的用戶不可見。 使用動臂日曆同步功能時，請設置名稱以區分您的日曆。",
    "General Info" : "基本信息",
    "Venue" : "會場",
    "Organizer"  : "組織者"
};

export default zh;
